// Maps every node class to its React component — one row per node.

import type { Emit } from "./components/nodeKit";
import { ClassicPreset } from "rete";
import type { JSXElementConstructor } from "react";
import {
  AngleDialNode, SlicerNode, CableSwitchNode, NoteNode, ReportNode, SessionHistoryNode, PresentationNode, ImageNode, FileLinkNode, SvgPickerNode, QrCodeNode,
  SparklineNode, ChartNode, MergePlotsNode, HistogramNode, KpiNode, ProportionNode, SankeyNode, SurfaceNode, MermaidNode, GaugeNode, HeatmapCellNode, ChartBuilderNode, DateInputNode, DateRangeNode, XYPadNode,
  WaterfallNode, CandlestickNode, BoxplotNode, CalendarHeatmapNode, QuiverNode, SevenSegNode, RecordNode,
  PointPlotterNode, CurveNode, GridPainterNode,
  FillBlanksNode, ReplaceValuesNode, MergeColumnsNode, HeadersNode, DropBlankRowsNode, DescribeNode, CorrMatrixNode, KMeansNode, PcaNode, LogisticNode, WindowNode,
  NumberInputNode, ArithmeticNode, DisplayNode, ComparisonNode, MathFnNode,
  ColorPickerNode, SaveTimesNode,
  ColorBlendNode,
  ClampNode, BooleanOpNode, NotNode, IfNode, ConduitNode, CastNode, ConstantNode, MRoundNode,
  ListInputNode, AggregateNode, SeriesNode, ListLengthNode, ListIndexNode,
  SortNode, ReverseNode, SliceNode, FilterNode, SumIfsNode, FillNode, XLookupNode,
  GcdNode, IFErrorNode, RandBetweenNode, RoundNNode, ConvertNode,
  UniqueNode, SetNode, ConcatListsNode, FrameFromListsNode, QuadraticRootsNode, PolyRootsNode, RunningNode, DiffNode,
  ArgMinMaxNode, ContainsNode, RankPercentileNode,
  CorrelNode, BesselNode, CombinatoricsNode, TwoInputMathNode,
  SumProductNode, ChooseNode, BooleanInputNode, SliderInputNode, IsTestNode,
  NaNode, AlertNode, NormalizeNode, BinNode, OutliersNode, SmoothNode, FindPeaksNode, ShiftNode, CombinationsNode, EwmaNode, ConvolveNode, CrossNode, PolyfitNode, TrapzNode, RleNode, BetweenNode, IsCloseNode,
  ShuffleNode, NthElementNode, InterleaveNode, PadNode,
  StandardizeNode, CovarianceNode, FisherNode, BitwiseNode,
  DepreciationNode,
  TvmNode, PaymentBreakdownNode, NpvNode, IrrNode, MirrNode, AmortizationNode, ReturnsNode,
  DistributionNode,
  RegressionNode, ForecastNode, ModeNode, TrimMeanNode, FrequencyNode, ConfidenceNode,
  SeriesSumNode, MultinomialNode, SwitchNode, IfsNode,
  HypothesisTestNode,
  EtsForecastNode, DecomposeNode, OdeIntegrateNode, FitDistributionNode, InterpolateNode, LinestNode, BinomDistRangeNode,
  FvScheduleNode, IspmtNode, DollarNode, ProbNode,
  WeightedNode, BaseConvertNode,
  TextInputNode, TextTransformNode, TextLenNode, ConcatNode, TextSliceNode,
  TextFindNode, SubstituteNode, TextReplaceNode,
  ReptNode, PadTextNode, TruncateTextNode, WrapTextNode, ExactNode, TextSimilarityNode, FuzzyMatchNode,
  CharCodeNode, TextJoinNode, TextSplitNode, TextAfterBeforeNode,
  NumberValueNode, RomanArabicNode, FixedNode, UrlEncodeNode, HashNode, UuidNode, TemplateNode,
  TodayNowNode, DateConstructNode, TimeConstructNode,
  DateTimeValueNode, DatePartNode, WeekInfoNode,
  DateDiffNode, DateAddNode, WorkdaysNode, EpochNode, DateTruncNode,
  TimeZoneConvertNode, WorldClockNode,
  RandArrayNode,
  XMatchNode,
  DiscountSecurityNode, CouponNode, AccruedInterestNode, DurationNode,
  BondPricingNode,
  ComplexFromNode, ComplexUnpackNode, ComplexUnaryNode, ComplexBinaryNode, ComplexPowerNode,
  TableInputNode, MatDetNode, MatSolveNode, MatEigenNode, SpectrumNode, TableMultNode, TableUnitNode, TableDiagNode, TableOuterNode, TableTransposeNode,
  StackNode, TableReshapeNode, TableSelectNode, TakeDropNode, ExpandNode, SetCellNode, TableInfoNode,
  MapTableNode, ByAxisNode, MakeArrayNode, ReduceLambdaNode, ScanLambdaNode, LambdaNode,
  FrameInputNode, BuildFrameNode, SplitFrameNode, GetColumnNode, AddColumnNode, ComputedColumnNode, GetRowNode, DistinctNode,
  HeadNode, SortFrameNode, FilterFrameNode, JoinNode,
  ColumnsNode, GroupByFrameNode, PivotNode, UnpivotNode, NestNode, UnnestNode, AppendNode, BindColumnsNode, RenameNode,
  SplitColumnNode, AddIndexNode, DecisionMatrixNode, DecisionSensitivityNode, AllocatorNode, ScheduleNode,
  ReconcileNode,
  BuildCubeNode, NestJoinNode, CubeColumnsNode, CubeRollupNode,
  WebSourceNode, LocalFileNode, ImportHtmlNode, ImportXmlNode, DataFeedNode, GeocodeNode, WeatherNode, HolidaysNode, FxNode, VaultFolderNode, TaskNotesNode,
  WriteFileNode, WriteObsidianNode, WriteTasksNode, ImportObsidianNode,
  GroupNode,
  CompositeNode, CompositeInputNode, CompositeOutputNode,
  IsEvenOddNode, FormatDollarNode,
  FormatControllerNode,
  ExpressionNode,
  ScriptNode,
  EquationNode,
  RegexNode,
  GroupByNode,
  ParallelCombineNode, ESeriesNode, AwgNode,
  PhysicsConstantNode,
  ColebrookNode,
  IsaAtmosphereNode, AntoineNode,
  IsInNode, TallyNode,
  ReverseTextNode, SpellNumberNode,
  SolarPositionNode, SunriseSunsetNode, MoonPhaseNode,
  ElementNode, MolarMassNode, ResistorCodeNode, EmSpectrumNode, HrZonesNode, PipeRoughnessNode, TriangleSolverNode,
  PromoNode,
  PlaceholderNode,
  ExpectNode,
  TornadoNode,
} from "./rete-nodes";
import {
  AngleDialComponent, SlicerComponent, CableSwitchComponent, NoteComponent, ReportComponent, SessionHistoryComponent, PresentationComponent, ImageComponent, FileLinkComponent, SvgPickerComponent, QrCodeComponent,
  SparklineComponent, ChartComponent, MergePlotsComponent, HistogramComponent, KpiComponent, ProportionComponent, SankeyComponent, SurfaceComponent, MermaidComponent, GaugeComponent, HeatmapCellComponent, ChartBuilderComponent, DateInputComponent, DateRangeComponent, XYPadComponent,
  WaterfallComponent, CandlestickComponent, BoxplotComponent, CalendarHeatmapComponent, QuiverComponent, SevenSegComponent, RecordComponent,
  PointPlotterComponent, CurveComponent, GridPainterComponent,
  FillBlanksComponent, ReplaceValuesComponent, MergeColumnsComponent, HeadersComponent, DropBlankRowsComponent,
  NumberInputComponent, ArithmeticComponent, DisplayComponent, ComparisonComponent,
  MathFnComponent, ClampComponent, BooleanComponent, NotComponent, IfComponent, ConduitComponent, CastComponent,
  ConstantComponent, MRoundComponent, ListInputComponent, AggregateComponent,
  SeriesComponent, ListLengthComponent, ListIndexComponent, SortComponent,
  ReverseComponent, SliceComponent, FilterComponent, SumIfsComponent, FillComponent,
  XLookupComponent, GcdComponent, IFErrorComponent, RandBetweenComponent,
  RoundNComponent, ConvertComponent, UniqueComponent, SetComponent,
  ConcatListsComponent, FrameFromListsComponent, QuadraticRootsComponent, PolyRootsComponent, RunningComponent, DiffComponent, ArgMinMaxComponent,
  ContainsComponent, RankPercentileComponent, CorrelComponent, CombinatoricsComponent,
  TwoInputMathComponent, SumProductComponent, ChooseComponent, BooleanInputComponent,
  SliderInputComponent, ColorPickerComponent, ColorBlendComponent, IsTestComponent, NaComponent, AlertComponent,
  NormalizeComponent, BinComponent, OutliersComponent, SmoothComponent, FindPeaksComponent, EpochComponent, DateTruncComponent, ShiftComponent, CombinationsComponent, EwmaComponent, ConvolveComponent, CrossComponent, PolyfitComponent, TrapzComponent, RleComponent, BetweenComponent, IsCloseComponent, ShuffleComponent,
  NthElementComponent, InterleaveComponent, PadComponent,
  StandardizeComponent, CovarianceComponent, FisherComponent,
  BesselComponent, BitwiseComponent, DepreciationComponent,
  TvmComponent, PaymentBreakdownComponent, NpvComponent, IrrComponent,
  MirrComponent, AmortizationComponent, ReturnsComponent, DescribeComponent, CorrMatrixComponent, KMeansComponent, PcaComponent, LogisticComponent, WindowComponent,
  DistributionComponent,
  RegressionComponent, ForecastComponent, ModeComponent, TrimMeanComponent,
  FrequencyComponent, ConfidenceComponent, SeriesSumComponent, MultinomialComponent,
  SwitchComponent, IfsComponent,
  HypothesisTestComponent,
  EtsForecastComponent, DecomposeComponent, OdeIntegrateComponent, FitDistributionComponent, InterpolateComponent, LinestComponent, BinomDistRangeComponent,
  FvScheduleComponent, IspmtComponent, DollarComponent, ProbComponent,
  WeightedComponent, BaseConvertComponent,
  TextInputComponent, TextTransformComponent, TextLenComponent, ConcatComponent,
  TextSliceComponent, TextFindComponent, SubstituteComponent, TextReplaceComponent,
  ReptComponent, PadTextComponent, TruncateTextComponent, WrapTextComponent, ExactComponent, TextSimilarityComponent, FuzzyMatchComponent,
  CharCodeComponent, TextJoinComponent, TextSplitComponent, TextAfterBeforeComponent,
  NumberValueComponent, RomanArabicComponent, FixedComponent, UrlEncodeComponent, HashComponent, UuidComponent, TemplateComponent,
  SaveTimesComponent,
  TodayNowComponent, DateConstructComponent, TimeConstructComponent,
  DateTimeValueComponent, DatePartComponent,
  WeekInfoComponent, DateDiffComponent, DateAddComponent,
  WorkdaysComponent, TimeZoneConvertComponent, WorldClockComponent,
  RandArrayComponent,
  XMatchComponent,
  DiscountSecurityComponent, CouponComponent, AccruedInterestComponent, DurationComponent,
  BondPricingComponent,
  ComplexFromComponent, ComplexUnpackComponent, ComplexUnaryComponent, ComplexBinaryComponent, ComplexPowerComponent,
  TableInputComponent, MatDetComponent, MatSolveComponent, MatEigenComponent, SpectrumComponent, TableMultComponent, TableUnitComponent, TableDiagComponent, TableOuterComponent, TableTransposeComponent,
  StackComponent, TableReshapeComponent, TableSelectComponent, TakeDropComponent, ExpandTableComponent, SetCellComponent, TableInfoComponent,
  MapTableComponent, ByAxisComponent, MakeArrayComponent, ReduceLambdaComponent, ScanLambdaComponent, LambdaComponent,
  FrameInputComponent, BuildFrameComponent, SplitFrameComponent, GetColumnComponent, AddColumnComponent, ComputedColumnComponent, GetRowComponent,
  DistinctComponent, HeadComponent, SortFrameComponent, FilterFrameComponent, JoinComponent,
  ColumnsComponent, GroupByFrameComponent, PivotComponent, UnpivotComponent,
  NestComponent, UnnestComponent, AppendComponent, BindColumnsComponent, RenameComponent,
  SplitColumnComponent, AddIndexComponent, DecisionMatrixComponent, DecisionSensitivityComponent, AllocatorComponent, ScheduleComponent,
  ReconcileComponent,
  BuildCubeComponent, NestJoinComponent, CubeColumnsComponent, CubeRollupComponent,
  WebSourceComponent, LocalFileComponent, ImportHtmlComponent, ImportXmlComponent, DataFeedComponent, GeocodeComponent, WeatherComponent, HolidaysComponent, FxComponent, VaultFolderComponent, TaskNotesComponent,
  WriteFileComponent, WriteObsidianComponent, WriteTasksComponent, ImportObsidianComponent,
  GroupComponent,
  CompositeComponent, CompositeInputMarkerComponent, CompositeOutputMarkerComponent,
  FormatDollarComponent, IsEvenOddComponent,
  FormatControllerComponent,
  ExpressionComponent,
  ScriptComponent,
  EquationComponent,
  RegexComponent,
  GroupByComponent,
  ParallelCombineComponent, ESeriesComponent, AwgComponent,
  PhysicsConstantComponent,
  ColebrookComponent,
  IsaAtmosphereComponent, AntoineComponent,
  IsInComponent, TallyComponent,
  ReverseTextComponent, SpellNumberComponent,
  SolarPositionComponent, SunriseSunsetComponent, MoonPhaseComponent,
  ElementComponent, MolarMassComponent, ResistorCodeComponent,
  PromoComponent,
  PlaceholderComponent,
  ExpectComponent,
  TornadoComponent,
} from "./components";
import { EmSpectrumComponent, HrZonesComponent, PipeRoughnessComponent, TriangleSolverComponent } from "./components/PackToolNodes";

export type AnyNodeComponent = JSXElementConstructor<{
  data: ClassicPreset.Node & { width?: number; height?: number };
  emit: Emit;
}>;

type NodeCtor = abstract new (...args: never[]) => ClassicPreset.Node;

const comp = (c: unknown) => c as unknown as AnyNodeComponent;

export const NODE_COMPONENTS: ReadonlyArray<readonly [NodeCtor, AnyNodeComponent]> = [
  [AngleDialNode,   comp(AngleDialComponent)],
  [SlicerNode,      comp(SlicerComponent)],
  [CableSwitchNode, comp(CableSwitchComponent)],
  [ImportObsidianNode, comp(ImportObsidianComponent)],
  [NoteNode,        comp(NoteComponent)],
  [ReportNode,      comp(ReportComponent)],
  [SessionHistoryNode, comp(SessionHistoryComponent)],
  [PresentationNode, comp(PresentationComponent)],
  [ImageNode,       comp(ImageComponent)],
  [FileLinkNode,    comp(FileLinkComponent)],
  [SvgPickerNode,   comp(SvgPickerComponent)],
  [QrCodeNode,      comp(QrCodeComponent)],
  [SparklineNode,   comp(SparklineComponent)],
  [ChartNode,       comp(ChartComponent)],
  [MergePlotsNode,  comp(MergePlotsComponent)],
  [HistogramNode,   comp(HistogramComponent)],
  [KpiNode,         comp(KpiComponent)],
  [ProportionNode,  comp(ProportionComponent)],
  [SankeyNode,      comp(SankeyComponent)],
  [SurfaceNode,     comp(SurfaceComponent)],
  [WaterfallNode,   comp(WaterfallComponent)],
  [CandlestickNode, comp(CandlestickComponent)],
  [BoxplotNode,     comp(BoxplotComponent)],
  [CalendarHeatmapNode, comp(CalendarHeatmapComponent)],
  [QuiverNode,      comp(QuiverComponent)],
  [SevenSegNode,    comp(SevenSegComponent)],
  [RecordNode,      comp(RecordComponent)],
  [PointPlotterNode, comp(PointPlotterComponent)],
  [CurveNode,       comp(CurveComponent)],
  [GridPainterNode, comp(GridPainterComponent)],
  [FillBlanksNode,   comp(FillBlanksComponent)],
  [ReplaceValuesNode, comp(ReplaceValuesComponent)],
  [MergeColumnsNode, comp(MergeColumnsComponent)],
  [HeadersNode, comp(HeadersComponent)],
  [DropBlankRowsNode, comp(DropBlankRowsComponent)],
  [DescribeNode,      comp(DescribeComponent)],
  [CorrMatrixNode,    comp(CorrMatrixComponent)],
  [KMeansNode,        comp(KMeansComponent)],
  [PcaNode,           comp(PcaComponent)],
  [LogisticNode,      comp(LogisticComponent)],
  [WindowNode,        comp(WindowComponent)],
  [MermaidNode,     comp(MermaidComponent)],
  [GaugeNode,       comp(GaugeComponent)],
  [HeatmapCellNode, comp(HeatmapCellComponent)],
  [ChartBuilderNode, comp(ChartBuilderComponent)],
  [DateInputNode,  comp(DateInputComponent)],
  [DateRangeNode,   comp(DateRangeComponent)],
  [XYPadNode,       comp(XYPadComponent)],
  [NumberInputNode, comp(NumberInputComponent)],
  [ArithmeticNode,  comp(ArithmeticComponent)],
  [DisplayNode,     comp(DisplayComponent)],
  [ComparisonNode,  comp(ComparisonComponent)],
  [MathFnNode,      comp(MathFnComponent)],
  [ClampNode,       comp(ClampComponent)],
  [BooleanOpNode,   comp(BooleanComponent)],
  [NotNode,         comp(NotComponent)],
  [IfNode,          comp(IfComponent)],
  [ConduitNode,      comp(ConduitComponent)],
  [CastNode,        comp(CastComponent)],
  [ConstantNode,    comp(ConstantComponent)],
  [MRoundNode,      comp(MRoundComponent)],
  [ListInputNode, comp(ListInputComponent)],
  [AggregateNode,   comp(AggregateComponent)],
  [SeriesNode,      comp(SeriesComponent)],
  [ListLengthNode,  comp(ListLengthComponent)],
  [ListIndexNode,   comp(ListIndexComponent)],
  [SortNode,        comp(SortComponent)],
  [ReverseNode,     comp(ReverseComponent)],
  [SliceNode,       comp(SliceComponent)],
  [SumIfsNode,       comp(SumIfsComponent)],
  [FilterNode,      comp(FilterComponent)],
  [FillNode,        comp(FillComponent)],
  [XLookupNode,     comp(XLookupComponent)],
  [GcdNode,         comp(GcdComponent)],
  [IFErrorNode,     comp(IFErrorComponent)],
  [RandBetweenNode, comp(RandBetweenComponent)],
  [RoundNNode,      comp(RoundNComponent)],
  [ConvertNode,     comp(ConvertComponent)],
  [UniqueNode,      comp(UniqueComponent)],
  [SetNode,         comp(SetComponent)],
  [ConcatListsNode, comp(ConcatListsComponent)],
  [FrameFromListsNode, comp(FrameFromListsComponent)],
  [QuadraticRootsNode, comp(QuadraticRootsComponent)],
  [PolyRootsNode,      comp(PolyRootsComponent)],
  [RunningNode,     comp(RunningComponent)],
  [DiffNode,        comp(DiffComponent)],
  [BinNode,         comp(BinComponent)],
  [OutliersNode,    comp(OutliersComponent)],
  [SmoothNode,      comp(SmoothComponent)],
  [FindPeaksNode,   comp(FindPeaksComponent)],
  [EpochNode,       comp(EpochComponent)],
  [DateTruncNode,   comp(DateTruncComponent)],
  [ShiftNode,       comp(ShiftComponent)],
  [CombinationsNode, comp(CombinationsComponent)],
  [EwmaNode,        comp(EwmaComponent)],
  [ConvolveNode,    comp(ConvolveComponent)],
  [CrossNode,       comp(CrossComponent)],
  [PolyfitNode,     comp(PolyfitComponent)],
  [TrapzNode,       comp(TrapzComponent)],
  [RleNode,         comp(RleComponent)],
  [BetweenNode,     comp(BetweenComponent)],
  [IsCloseNode,     comp(IsCloseComponent)],
  [ArgMinMaxNode,   comp(ArgMinMaxComponent)],
  [ContainsNode,    comp(ContainsComponent)],
  [RankPercentileNode, comp(RankPercentileComponent)],
  [CorrelNode,      comp(CorrelComponent)],
  [BesselNode,        comp(BesselComponent)],
  [CombinatoricsNode, comp(CombinatoricsComponent)],
  [TwoInputMathNode,  comp(TwoInputMathComponent)],
  [SumProductNode,    comp(SumProductComponent)],
  [ChooseNode,        comp(ChooseComponent)],
  [BooleanInputNode,  comp(BooleanInputComponent)],
  [SliderInputNode,   comp(SliderInputComponent)],
  [ColorPickerNode,   comp(ColorPickerComponent)],
  [ColorBlendNode,    comp(ColorBlendComponent)],
  [IsTestNode,      comp(IsTestComponent)],
  [NaNode,          comp(NaComponent)],
  [AlertNode,       comp(AlertComponent)],
  [NormalizeNode,   comp(NormalizeComponent)],
  [ShuffleNode,     comp(ShuffleComponent)],
  [NthElementNode,  comp(NthElementComponent)],
  [InterleaveNode,  comp(InterleaveComponent)],
  [PadNode,         comp(PadComponent)],
  [StandardizeNode, comp(StandardizeComponent)],
  [CovarianceNode,  comp(CovarianceComponent)],
  [FisherNode,      comp(FisherComponent)],
  [BitwiseNode,     comp(BitwiseComponent)],
  [DepreciationNode, comp(DepreciationComponent)],
  // Must stay ABOVE EquationNode — the subclass fallback is an instanceof SCAN.
  [TvmNode,          comp(TvmComponent)],
  [PaymentBreakdownNode, comp(PaymentBreakdownComponent)],
  [NpvNode,          comp(NpvComponent)],
  [IrrNode,          comp(IrrComponent)],
  [MirrNode,         comp(MirrComponent)],
  [AmortizationNode, comp(AmortizationComponent)],
  [ReturnsNode,      comp(ReturnsComponent)],
  [DistributionNode, comp(DistributionComponent)],
  [RegressionNode,   comp(RegressionComponent)],
  [ForecastNode,     comp(ForecastComponent)],
  [ModeNode,         comp(ModeComponent)],
  [TrimMeanNode,     comp(TrimMeanComponent)],
  [FrequencyNode,    comp(FrequencyComponent)],
  [ConfidenceNode,   comp(ConfidenceComponent)],
  [SeriesSumNode,    comp(SeriesSumComponent)],
  [MultinomialNode,  comp(MultinomialComponent)],
  [SwitchNode,       comp(SwitchComponent)],
  [IfsNode,          comp(IfsComponent)],
  [HypothesisTestNode, comp(HypothesisTestComponent)],
  [EtsForecastNode,  comp(EtsForecastComponent)],
  [DecomposeNode,    comp(DecomposeComponent)],
  [OdeIntegrateNode, comp(OdeIntegrateComponent)],
  [FitDistributionNode, comp(FitDistributionComponent)],
  [InterpolateNode,  comp(InterpolateComponent)],
  [LinestNode,       comp(LinestComponent)],
  [BinomDistRangeNode, comp(BinomDistRangeComponent)],
  [FvScheduleNode,   comp(FvScheduleComponent)],
  [IspmtNode,        comp(IspmtComponent)],
  [DollarNode,       comp(DollarComponent)],
  [ProbNode,         comp(ProbComponent)],
  [WeightedNode,     comp(WeightedComponent)],
  [BaseConvertNode,  comp(BaseConvertComponent)],
  [TextInputNode,  comp(TextInputComponent)],
  [TextTransformNode,comp(TextTransformComponent)],
  [TextLenNode,      comp(TextLenComponent)],
  [ConcatNode,       comp(ConcatComponent)],
  [TextSliceNode,    comp(TextSliceComponent)],
  [TextFindNode,     comp(TextFindComponent)],
  [SubstituteNode,   comp(SubstituteComponent)],
  [TextReplaceNode,  comp(TextReplaceComponent)],
  [ReptNode,              comp(ReptComponent)],
  [PadTextNode,           comp(PadTextComponent)],
  [TruncateTextNode,      comp(TruncateTextComponent)],
  [WrapTextNode,          comp(WrapTextComponent)],
  [ExactNode,             comp(ExactComponent)],
  [TextSimilarityNode, comp(TextSimilarityComponent)],
  [FuzzyMatchNode,     comp(FuzzyMatchComponent)],
  [CharCodeNode,          comp(CharCodeComponent)],
  [TextJoinNode,          comp(TextJoinComponent)],
  [TextSplitNode,         comp(TextSplitComponent)],
  [TextAfterBeforeNode,   comp(TextAfterBeforeComponent)],
  [NumberValueNode,       comp(NumberValueComponent)],
  [RomanArabicNode,       comp(RomanArabicComponent)],
  [FixedNode,             comp(FixedComponent)],
  [UrlEncodeNode,         comp(UrlEncodeComponent)],
  [HashNode,              comp(HashComponent)],
  [TemplateNode,          comp(TemplateComponent)],
  [UuidNode,              comp(UuidComponent)],
  [SaveTimesNode,         comp(SaveTimesComponent)],
  [TodayNowNode,          comp(TodayNowComponent)],
  [DateConstructNode,     comp(DateConstructComponent)],
  [TimeConstructNode,     comp(TimeConstructComponent)],
  [DateTimeValueNode,     comp(DateTimeValueComponent)],
  [DatePartNode,          comp(DatePartComponent)],
  [WeekInfoNode,          comp(WeekInfoComponent)],
  [DateDiffNode,          comp(DateDiffComponent)],
  [DateAddNode,           comp(DateAddComponent)],
  [WorkdaysNode,          comp(WorkdaysComponent)],
  [TimeZoneConvertNode,   comp(TimeZoneConvertComponent)],
  [WorldClockNode,        comp(WorldClockComponent)],
  [RandArrayNode,         comp(RandArrayComponent)],
  [XMatchNode,            comp(XMatchComponent)],
  [DiscountSecurityNode,  comp(DiscountSecurityComponent)],
  [CouponNode,            comp(CouponComponent)],
  [AccruedInterestNode,   comp(AccruedInterestComponent)],
  [DurationNode,          comp(DurationComponent)],
  [BondPricingNode,       comp(BondPricingComponent)],
  [IsEvenOddNode,         comp(IsEvenOddComponent)],
  [FormatDollarNode,      comp(FormatDollarComponent)],
  [TableInputNode,        comp(TableInputComponent)],
  [MatSolveNode,     comp(MatSolveComponent)],
  [MatEigenNode,     comp(MatEigenComponent)],
  [SpectrumNode,     comp(SpectrumComponent)],
  [MatDetNode,            comp(MatDetComponent)],
  [TableMultNode,         comp(TableMultComponent)],
  [TableUnitNode,         comp(TableUnitComponent)],
  [TableDiagNode,         comp(TableDiagComponent)],
  [TableOuterNode,        comp(TableOuterComponent)],
  [TableTransposeNode,    comp(TableTransposeComponent)],
  [StackNode,             comp(StackComponent)],
  [TableReshapeNode,      comp(TableReshapeComponent)],
  [TableSelectNode,       comp(TableSelectComponent)],
  [TakeDropNode,          comp(TakeDropComponent)],
  [ExpandNode,            comp(ExpandTableComponent)],
  [SetCellNode,           comp(SetCellComponent)],
  [TableInfoNode,         comp(TableInfoComponent)],
  [MapTableNode,          comp(MapTableComponent)],
  [ByAxisNode,            comp(ByAxisComponent)],
  [MakeArrayNode,         comp(MakeArrayComponent)],
  [ReduceLambdaNode,      comp(ReduceLambdaComponent)],
  [ScanLambdaNode,        comp(ScanLambdaComponent)],
  [LambdaNode,            comp(LambdaComponent)],
  [FrameInputNode,        comp(FrameInputComponent)],
  [WebSourceNode,         comp(WebSourceComponent)],
  [GeocodeNode,           comp(GeocodeComponent)],
  [WeatherNode,           comp(WeatherComponent)],
  [HolidaysNode,          comp(HolidaysComponent)],
  [TaskNotesNode,         comp(TaskNotesComponent)],
  [FxNode,                comp(FxComponent)],
  [VaultFolderNode,       comp(VaultFolderComponent)],
  [DataFeedNode,          comp(DataFeedComponent)],
  [LocalFileNode,         comp(LocalFileComponent)],
  [ImportHtmlNode,        comp(ImportHtmlComponent)],
  [ImportXmlNode,         comp(ImportXmlComponent)],
  [WriteFileNode,         comp(WriteFileComponent)],
  [WriteObsidianNode,     comp(WriteObsidianComponent)],
  [WriteTasksNode,        comp(WriteTasksComponent)],
  [BuildFrameNode,        comp(BuildFrameComponent)],
  [SplitFrameNode,        comp(SplitFrameComponent)],
  [GetColumnNode,         comp(GetColumnComponent)],
  [AddColumnNode,         comp(AddColumnComponent)],
  [ComputedColumnNode,    comp(ComputedColumnComponent)],
  [GetRowNode,            comp(GetRowComponent)],
  [DistinctNode,          comp(DistinctComponent)],
  [HeadNode,              comp(HeadComponent)],
  [SortFrameNode,         comp(SortFrameComponent)],
  [FilterFrameNode,       comp(FilterFrameComponent)],
  [JoinNode,              comp(JoinComponent)],
  [ColumnsNode,           comp(ColumnsComponent)],
  [GroupByFrameNode,      comp(GroupByFrameComponent)],
  [PivotNode,             comp(PivotComponent)],
  [UnpivotNode,           comp(UnpivotComponent)],
  [NestNode,              comp(NestComponent)],
  [UnnestNode,            comp(UnnestComponent)],
  [AppendNode,            comp(AppendComponent)],
  [BindColumnsNode,       comp(BindColumnsComponent)],
  [RenameNode,            comp(RenameComponent)],
  [SplitColumnNode,       comp(SplitColumnComponent)],
  [AddIndexNode,          comp(AddIndexComponent)],
  [DecisionMatrixNode,    comp(DecisionMatrixComponent)],
  [DecisionSensitivityNode, comp(DecisionSensitivityComponent)],
  [ScheduleNode, comp(ScheduleComponent)],
  [AllocatorNode,         comp(AllocatorComponent)],
  [ReconcileNode,         comp(ReconcileComponent)],
  [BuildCubeNode,         comp(BuildCubeComponent)],
  [NestJoinNode,          comp(NestJoinComponent)],
  [CubeColumnsNode,       comp(CubeColumnsComponent)],
  [CubeRollupNode,        comp(CubeRollupComponent)],
  [GroupNode,             comp(GroupComponent)],
  [CompositeNode,         comp(CompositeComponent)],
  // Boundary markers — rendered only inside the drill-in editor's own rete root.
  [CompositeInputNode,    comp(CompositeInputMarkerComponent)],
  [CompositeOutputNode,   comp(CompositeOutputMarkerComponent)],
  [ComplexFromNode,       comp(ComplexFromComponent)],
  [ComplexUnpackNode,     comp(ComplexUnpackComponent)],
  [ComplexUnaryNode,      comp(ComplexUnaryComponent)],
  [ComplexBinaryNode,     comp(ComplexBinaryComponent)],
  [ComplexPowerNode,      comp(ComplexPowerComponent)],
  [FormatControllerNode,  comp(FormatControllerComponent)],
  [ExpressionNode,        comp(ExpressionComponent)],
  [ScriptNode,            comp(ScriptComponent)],
  [EquationNode,          comp(EquationComponent)],
  [RegexNode,             comp(RegexComponent)],
  [GroupByNode,           comp(GroupByComponent)],
  // Packs: registered ALWAYS, so a saved graph renders with the pack deactivated.
  [ParallelCombineNode,   comp(ParallelCombineComponent)],
  [ESeriesNode,           comp(ESeriesComponent)],
  [AwgNode,               comp(AwgComponent)],
  [PhysicsConstantNode,   comp(PhysicsConstantComponent)],
  [ColebrookNode,         comp(ColebrookComponent)],
  [IsaAtmosphereNode,     comp(IsaAtmosphereComponent)],
  [AntoineNode,           comp(AntoineComponent)],
  [IsInNode,              comp(IsInComponent)],
  [TallyNode,             comp(TallyComponent)],
  [ReverseTextNode,       comp(ReverseTextComponent)],
  [SpellNumberNode,       comp(SpellNumberComponent)],
  [SolarPositionNode,     comp(SolarPositionComponent)],
  [SunriseSunsetNode,     comp(SunriseSunsetComponent)],
  [MoonPhaseNode,         comp(MoonPhaseComponent)],
  [ElementNode,           comp(ElementComponent)],
  [ResistorCodeNode,      comp(ResistorCodeComponent)],
  [EmSpectrumNode,        comp(EmSpectrumComponent)],
  [HrZonesNode,           comp(HrZonesComponent)],
  [PipeRoughnessNode,     comp(PipeRoughnessComponent)],
  [TriangleSolverNode,    comp(TriangleSolverComponent)],
  [MolarMassNode,         comp(MolarMassComponent)],
  [PromoNode,             comp(PromoComponent)],
  // Load-time stand-in for an unregistered saved type (pack off / renamed).
  [PlaceholderNode,       comp(PlaceholderComponent)],
  [ExpectNode,            comp(ExpectComponent)],
  [TornadoNode,           comp(TornadoComponent)],
];

// Exact constructor first, then the ordered `instanceof` scan for subclasses that
// reuse a base component — so entry order matters only for UNregistered subclasses.
const componentByCtor = new Map<NodeCtor, AnyNodeComponent>(NODE_COMPONENTS);

export function componentForNode(payload: object): AnyNodeComponent | null {
  const exact = componentByCtor.get(payload.constructor as NodeCtor);
  if (exact) return exact;
  const hit = NODE_COMPONENTS.find(([Ctor]) => payload instanceof Ctor);
  return hit ? hit[1] : null;
}
