// The source of truth for each node's Excel equivalence, applied onto catalog leaves by
// buildCatalog; pack nodes may instead declare `excel` inline on their entry.
import type { ExcelEquiv } from "./AddNodeMenu";

/** catalog node type -> the Excel function(s) it stands in for. */
export const NODE_EXCEL: Record<string, ExcelEquiv[]> = {
  "accrued-interest": [
    { excel: "ACCRINT", syntax: "=ACCRINT(issue,settle,rate,par,freq,basis)", parity: false, note: "Accrued interest over the issue→settlement span; all four bases: 30/360, actual/actual, actual/360, actual/365. Excel's first_interest and calc_method arguments aren't modeled." },
    { excel: "ACCRINTM", syntax: "=ACCRINTM(issue,settle,rate,par,basis)", parity: false, note: "Accrued interest at maturity; all four bases: 30/360, actual/actual, actual/360, actual/365." },
  ],
  "arith-mod": [{ excel: "MOD", syntax: "=MOD(a, b)", parity: true }],
  "arith-pow": [{ excel: "POWER", syntax: "=POWER(x, n)", parity: true }],
  "arith-quotient": [{ excel: "QUOTIENT", syntax: "=QUOTIENT(a, b)", parity: true }],
  "base-convert": [
    { excel: "BASE", syntax: "=BASE(n, radix)", parity: false, note: "Excel outputs text; Solenoid outputs a number, so A–F digits aren't representable" },
    { excel: "DECIMAL", syntax: "=DECIMAL(text, radix)", parity: false, note: "Excel takes a text string; Solenoid takes the decimal digit-string as a number" },
    { excel: "BIN2DEC", syntax: "=BIN2DEC(number)", parity: false, note: "Use Base Convert node: from=2, to=10" },
    { excel: "BIN2HEX", syntax: "=BIN2HEX(number)", parity: false, note: "Use Base Convert node with from=2, to=16; hex output returns null, no A–F" },
    { excel: "BIN2OCT", syntax: "=BIN2OCT(number)", parity: false, note: "Use Base Convert node: from=2, to=8" },
    { excel: "DEC2BIN", syntax: "=DEC2BIN(number)", parity: false, note: "Use Base Convert node: from=10, to=2" },
    { excel: "DEC2HEX", syntax: "=DEC2HEX(number)", parity: false, note: "Use Base Convert node with from=10, to=16; returns null when digits > 9" },
    { excel: "DEC2OCT", syntax: "=DEC2OCT(number)", parity: false, note: "Use Base Convert node: from=10, to=8" },
    { excel: "HEX2BIN", syntax: "=HEX2BIN(number)", parity: false, note: "Use Base Convert node with from=16, to=2; hex input digits A–F not enterable" },
    { excel: "HEX2DEC", syntax: "=HEX2DEC(number)", parity: false, note: "Use Base Convert node with from=16, to=10; hex input digits A–F not enterable" },
    { excel: "HEX2OCT", syntax: "=HEX2OCT(number)", parity: false, note: "Use Base Convert node with from=16, to=8; hex input digits A–F not enterable" },
    { excel: "OCT2BIN", syntax: "=OCT2BIN(number)", parity: false, note: "Use Base Convert node: from=8, to=2" },
    { excel: "OCT2DEC", syntax: "=OCT2DEC(number)", parity: false, note: "Use Base Convert node: from=8, to=10" },
    { excel: "OCT2HEX", syntax: "=OCT2HEX(number)", parity: false, note: "Use Base Convert node with from=8, to=16; hex output returns null, no A–F" },
  ],
  "bessel-besseli": [{ excel: "BESSELI", syntax: "=BESSELI(x, n)", parity: false, note: "x must be ≥ 0; n must be a non-negative integer" }],
  "bessel-besselj": [{ excel: "BESSELJ", syntax: "=BESSELJ(x, n)", parity: false, note: "n must be a non-negative integer" }],
  "bessel-besselk": [{ excel: "BESSELK", syntax: "=BESSELK(x, n)", parity: false, note: "x must be > 0; n must be a non-negative integer" }],
  "bessel-bessely": [{ excel: "BESSELY", syntax: "=BESSELY(x, n)", parity: false, note: "x must be > 0; n must be a non-negative integer" }],
  "binomdistrng": [{ excel: "BINOM.DIST.RANGE", syntax: "=BINOM.DIST.RANGE(n, p, lo, hi)" }],
  "bitwise-bitand": [{ excel: "BITAND", syntax: "=BITAND(a, b)", parity: true }],
  "bitwise-bitlshift": [{ excel: "BITLSHIFT", syntax: "=BITLSHIFT(a, n)", parity: true }],
  "bitwise-bitor": [{ excel: "BITOR", syntax: "=BITOR(a, b)", parity: true }],
  "bitwise-bitrshift": [{ excel: "BITRSHIFT", syntax: "=BITRSHIFT(a, n)", parity: true }],
  "bitwise-bitxor": [{ excel: "BITXOR", syntax: "=BITXOR(a, b)", parity: true }],
  "bond-pricing": [
    { excel: "PRICE", syntax: "=PRICE(settle,maturity,rate,yld,redemption,freq)", parity: false, note: "30/360 basis only (no basis argument). Confirmed against Microsoft's worked example." },
    { excel: "YIELD", syntax: "=YIELD(settle,maturity,rate,pr,redemption,freq)", parity: false, note: "30/360 basis only" },
    { excel: "ODDFPRICE", syntax: "=ODDFPRICE(...)", parity: false, note: "30/360 basis only; a first coupon off the maturity's coupon cycle computes here where Excel gives #NUM!" },
    { excel: "ODDFYIELD", syntax: "=ODDFYIELD(...)", parity: false, note: "30/360 basis only; a first coupon off the maturity's coupon cycle computes here where Excel gives #NUM!" },
    { excel: "ODDLPRICE", syntax: "=ODDLPRICE(...)", parity: false, note: "30/360 basis only" },
    { excel: "ODDLYIELD", syntax: "=ODDLYIELD(...)", parity: false, note: "30/360 basis only" },
  ],
  "by-axis": [{ excel: "BYROW", syntax: "=BYROW(array, LAMBDA(values, ...))", parity: false, note: "Reduces each row with its own formula of (values), or a wired LAMBDA value" }],
  "by-col": [{ excel: "BYCOL", syntax: "=BYCOL(array, LAMBDA(values, ...))", parity: false, note: "Reduces each column with its own formula of (values), or a wired LAMBDA value" }],
  "char-code-char": [
    { excel: "CHAR", syntax: "=CHAR(code)", parity: false, note: "Full Unicode (=UNICHAR); code point 0–1114111" },
    { excel: "UNICHAR", syntax: "=UNICHAR(code)", parity: true, note: "Same as CHAR in Solenoid; full Unicode range" },
  ],
  "char-code-code": [
    { excel: "CODE", syntax: "=CODE(text)", parity: false, note: "Returns Unicode code point (=UNICODE); full Unicode range" },
    { excel: "UNICODE", syntax: "=UNICODE(text)", parity: true, note: "Same as CODE in Solenoid; full Unicode range" },
  ],
  "chisq-test": [{ excel: "CHISQ.TEST", syntax: "=CHISQ.TEST(obs, exp)" }],
  "choose": [{ excel: "CHOOSE", syntax: "=CHOOSE(idx, v1, v2, ...)", parity: true }],
  "comb-combin": [{ excel: "COMBIN", syntax: "=COMBIN(n, k)", parity: true }],
  "comb-combina": [{ excel: "COMBINA", syntax: "=COMBINA(n, k)", parity: true }],
  "comb-fact": [{ excel: "FACT", syntax: "=FACT(n)", parity: true }],
  "comb-factdouble": [{ excel: "FACTDOUBLE", syntax: "=FACTDOUBLE(n)", parity: true }],
  "comb-permut": [{ excel: "PERMUT", syntax: "=PERMUT(n, k)", parity: true }],
  "comb-permutationa": [{ excel: "PERMUTATIONA", syntax: "=PERMUTATIONA(n, k)" }],
  "confidence-norm": [{ excel: "CONFIDENCE.NORM", syntax: "=CONFIDENCE.NORM(α, σ, n)", parity: true }],
  "confidence-t": [{ excel: "CONFIDENCE.T", syntax: "=CONFIDENCE.T(α, σ, n)", parity: true }],
  "constant": [
    { excel: "PI", syntax: "=PI()", parity: true },
    { excel: "FALSE", syntax: "=FALSE()", parity: true },
    { excel: "TRUE", syntax: "=TRUE()", parity: true },
  ],
  "convert": [
    { excel: "CONVERT", syntax: "=CONVERT(x, from, to)", parity: true },
    { excel: "DEGREES", syntax: "=DEGREES(angle)", parity: true },
    { excel: "RADIANS", syntax: "=RADIANS(angle)", parity: true },
  ],
  "correl-correl": [
    { excel: "CORREL", syntax: "=CORREL(x, y)", parity: true },
    { excel: "PEARSON", syntax: "=PEARSON(x, y)", parity: true, note: "PEARSON = CORREL" },
  ],
  "coupon-coupdaybs": [{ excel: "COUPDAYBS", syntax: "=COUPDAYBS(settle,maturity,freq,basis)", parity: false, note: "Days from the coupon-period start to settlement; frequency 1/2/4, all four bases." }],
  "coupon-coupdays": [{ excel: "COUPDAYS", syntax: "=COUPDAYS(settle,maturity,freq,basis)", parity: false, note: "Days in the coupon period containing settlement; frequency 1/2/4, all four bases." }],
  "coupon-coupdaysnc": [{ excel: "COUPDAYSNC", syntax: "=COUPDAYSNC(settle,maturity,freq,basis)", parity: false, note: "Days from settlement to the next coupon; frequency 1/2/4, all four bases." }],
  "coupon-coupncd": [{ excel: "COUPNCD", syntax: "=COUPNCD(settle,maturity,freq)", parity: false, note: "Next coupon date after settlement, as a date serial; frequency 1/2/4." }],
  "coupon-coupnum": [{ excel: "COUPNUM", syntax: "=COUPNUM(settle,maturity,freq)", parity: false, note: "Number of coupons from settlement to maturity; frequency 1/2/4." }],
  "coupon-couppcd": [{ excel: "COUPPCD", syntax: "=COUPPCD(settle,maturity,freq)", parity: false, note: "Previous coupon date on or before settlement, as a date serial; frequency 1/2/4." }],
  "cov-pop": [{ excel: "COVARIANCE.P", syntax: "=COVARIANCE.P(x, y)", parity: true }],
  "cov-samp": [{ excel: "COVARIANCE.S", syntax: "=COVARIANCE.S(x, y)", parity: true }],
  "cx-binary-div": [{ excel: "IMDIV", syntax: "=IMDIV(z1, z2)", parity: false }],
  "cx-binary-product": [{ excel: "IMPRODUCT", syntax: "=IMPRODUCT(z1, z2)", parity: false }],
  "cx-binary-sub": [{ excel: "IMSUB", syntax: "=IMSUB(z1, z2)", parity: false }],
  "cx-binary-sum": [{ excel: "IMSUM", syntax: "=IMSUM(z1, z2)", parity: false }],
  "cx-from": [{ excel: "COMPLEX", syntax: "=COMPLEX(real, imag)", parity: false, note: "Solenoid uses a typed complex socket (sky-blue); Excel encodes as text strings like \"3+4i\"" }],
  "cx-power": [{ excel: "IMPOWER", syntax: "=IMPOWER(z, n)", parity: false, note: "n is a real exponent; complex exponent not supported" }],
  "cx-unary-conj": [{ excel: "IMCONJUGATE", syntax: "=IMCONJUGATE(z)", parity: false }],
  "cx-unary-cos": [{ excel: "IMCOS", syntax: "=IMCOS(z)", parity: false }],
  "cx-unary-cosh": [{ excel: "IMCOSH", syntax: "=IMCOSH(z)", parity: false }],
  "cx-unary-cot": [{ excel: "IMCOT", syntax: "=IMCOT(z)", parity: false }],
  "cx-unary-csc": [{ excel: "IMCSC", syntax: "=IMCSC(z)", parity: false }],
  "cx-unary-csch": [{ excel: "IMCSCH", syntax: "=IMCSCH(z)", parity: false }],
  "cx-unary-exp": [{ excel: "IMEXP", syntax: "=IMEXP(z)", parity: false }],
  "cx-unary-ln": [{ excel: "IMLN", syntax: "=IMLN(z)", parity: false }],
  "cx-unary-log10": [{ excel: "IMLOG10", syntax: "=IMLOG10(z)", parity: false }],
  "cx-unary-log2": [{ excel: "IMLOG2", syntax: "=IMLOG2(z)", parity: false }],
  "cx-unary-sec": [{ excel: "IMSEC", syntax: "=IMSEC(z)", parity: false }],
  "cx-unary-sech": [{ excel: "IMSECH", syntax: "=IMSECH(z)", parity: false }],
  "cx-unary-sin": [{ excel: "IMSIN", syntax: "=IMSIN(z)", parity: false }],
  "cx-unary-sinh": [{ excel: "IMSINH", syntax: "=IMSINH(z)", parity: false }],
  "cx-unary-sqrt": [{ excel: "IMSQRT", syntax: "=IMSQRT(z)", parity: false }],
  "cx-unary-tan": [{ excel: "IMTAN", syntax: "=IMTAN(z)", parity: false }],
  "cx-unpack": [
    { excel: "IMABS", syntax: "=IMABS(z)", parity: false, note: "Use IM Unpack node; exposes Real, Imag, |z|, arg(z) simultaneously" },
    { excel: "IMAGINARY", syntax: "=IMAGINARY(z)", parity: false, note: "Use IM Unpack node" },
    { excel: "IMREAL", syntax: "=IMREAL(z)", parity: false, note: "Use IM Unpack node" },
    { excel: "IMARGUMENT", syntax: "=IMARGUMENT(z)", parity: false, note: "Use IM Unpack node" },
  ],
  "date-add-edate": [{ excel: "EDATE", syntax: "=EDATE(start, months)", parity: false }],
  "date-add-eomonth": [{ excel: "EOMONTH", syntax: "=EOMONTH(start, months)", parity: false }],
  "date-construct": [{ excel: "DATE", syntax: "=DATE(year, month, day)", parity: false }],
  "date-datedif": [{ excel: "DATEDIF", syntax: "=DATEDIF(start, end, unit)", parity: false, note: "MD borrows from the month before the end month; where Excel's documented-unreliable MD goes negative (e.g. Jan 31 → Mar 1) results may differ" }],
  "date-diff-days": [{ excel: "DAYS", syntax: "=DAYS(end_date, start_date)", parity: false }],
  "date-diff-days360": [{ excel: "DAYS360", syntax: "=DAYS360(start, end)", parity: false }],
  "date-diff-yearfrac": [{ excel: "YEARFRAC", syntax: "=YEARFRAC(start, end)", parity: false, note: "basis 1 (actual/actual) is approximated as ÷365.25" }],
  "date-networkdays": [
    { excel: "NETWORKDAYS", syntax: "=NETWORKDAYS(start, end)", parity: false },
    { excel: "NETWORKDAYS.INTL", syntax: "=NETWORKDAYS.INTL(start, end, wknd)", parity: false, note: "Use NETWORKDAYS with weekend_code input" },
  ],
  "date-now": [{ excel: "NOW", syntax: "=NOW()", parity: false }],
  "date-part-day": [{ excel: "DAY", syntax: "=DAY(date)", parity: false }],
  "date-part-hour": [{ excel: "HOUR", syntax: "=HOUR(time)", parity: false }],
  "date-part-minute": [{ excel: "MINUTE", syntax: "=MINUTE(time)", parity: false }],
  "date-part-month": [{ excel: "MONTH", syntax: "=MONTH(date)", parity: false }],
  "date-part-second": [{ excel: "SECOND", syntax: "=SECOND(time)", parity: false }],
  "date-part-year": [{ excel: "YEAR", syntax: "=YEAR(date)", parity: false }],
  "date-time": [{ excel: "TIME", syntax: "=TIME(hour, minute, second)", parity: false }],
  "date-today": [{ excel: "TODAY", syntax: "=TODAY()", parity: false }],
  "date-value": [{ excel: "DATEVALUE", syntax: "=DATEVALUE(date_text)", parity: false, note: "Wider than Excel: ISO, day-first numeric, ordinals and month names; a numeric date that could read either way is #AMBIGUOUS!, never a silent guess" }],
  "date-week-isoweeknum": [{ excel: "ISOWEEKNUM", syntax: "=ISOWEEKNUM(date)", parity: false }],
  "date-week-weekday": [{ excel: "WEEKDAY", syntax: "=WEEKDAY(date)", parity: false }],
  "date-week-weeknum": [{ excel: "WEEKNUM", syntax: "=WEEKNUM(date)", parity: false }],
  "date-workday": [
    { excel: "WORKDAY", syntax: "=WORKDAY(start, days)", parity: false },
    { excel: "WORKDAY.INTL", syntax: "=WORKDAY.INTL(start, days, wknd)", parity: false, note: "Use WORKDAY with weekend_code input" },
  ],
  "depr-db": [{ excel: "DB", syntax: "=DB(cost, salv, life, per)", parity: true }],
  "depr-ddb": [{ excel: "DDB", syntax: "=DDB(cost, salv, life, per)", parity: true }],
  "depr-sln": [{ excel: "SLN", syntax: "=SLN(cost, salv, life)", parity: true }],
  "depr-syd": [{ excel: "SYD", syntax: "=SYD(cost, salv, life, per)", parity: true }],
  "distribution": [
    { excel: "BETA.DIST", syntax: "=BETA.DIST(x, α, β, cum)", parity: true },
    { excel: "BETA.INV", syntax: "=BETA.INV(p, α, β)", parity: true },
    { excel: "BINOM.DIST", syntax: "=BINOM.DIST(k, n, p, cum)", parity: true },
    { excel: "BINOM.INV", syntax: "=BINOM.INV(n, p, α)" },
    { excel: "CHISQ.DIST", syntax: "=CHISQ.DIST(x, df, cum)", parity: true },
    { excel: "CHISQ.DIST.RT", syntax: "=CHISQ.DIST.RT(x, df)", parity: true },
    { excel: "CHISQ.INV", syntax: "=CHISQ.INV(p, df)", parity: true },
    { excel: "CHISQ.INV.RT", syntax: "=CHISQ.INV.RT(p, df)", parity: true },
    { excel: "EXPON.DIST", syntax: "=EXPON.DIST(x, λ, cum)" },
    { excel: "F.DIST", syntax: "=F.DIST(x, d1, d2, cum)", parity: true },
    { excel: "F.DIST.RT", syntax: "=F.DIST.RT(x, d1, d2)", parity: true },
    { excel: "F.INV", syntax: "=F.INV(p, d1, d2)", parity: true },
    { excel: "F.INV.RT", syntax: "=F.INV.RT(p, d1, d2)", parity: true },
    { excel: "GAMMA.DIST", syntax: "=GAMMA.DIST(x, α, β, cum)", parity: true },
    { excel: "GAMMA.INV", syntax: "=GAMMA.INV(p, α, β)", parity: true },
    { excel: "GAUSS", syntax: "=GAUSS(z)", parity: true },
    { excel: "HYPGEOM.DIST", syntax: "=HYPGEOM.DIST(s, ns, M, N, cum)" },
    { excel: "LOGNORM.DIST", syntax: "=LOGNORM.DIST(x, μ, σ, cum)" },
    { excel: "LOGNORM.INV", syntax: "=LOGNORM.INV(p, μ, σ)" },
    { excel: "NEGBINOM.DIST", syntax: "=NEGBINOM.DIST(k, r, p, cum)" },
    { excel: "NORM.DIST", syntax: "=NORM.DIST(x, μ, σ, cum)", parity: true },
    { excel: "NORM.INV", syntax: "=NORM.INV(p, μ, σ)", parity: true },
    { excel: "NORM.S.DIST", syntax: "=NORM.S.DIST(z, cum)", parity: true },
    { excel: "NORM.S.INV", syntax: "=NORM.S.INV(p)", parity: true },
    { excel: "PHI", syntax: "=PHI(x)", parity: true },
    { excel: "POISSON.DIST", syntax: "=POISSON.DIST(k, λ, cum)" },
    { excel: "T.DIST", syntax: "=T.DIST(x, df, cum)", parity: true },
    { excel: "T.DIST.2T", syntax: "=T.DIST.2T(x, df)", parity: true },
    { excel: "T.DIST.RT", syntax: "=T.DIST.RT(x, df)", parity: true },
    { excel: "T.INV", syntax: "=T.INV(p, df)", parity: true },
    { excel: "T.INV.2T", syntax: "=T.INV.2T(p, df)", parity: true },
    { excel: "WEIBULL.DIST", syntax: "=WEIBULL.DIST(x, α, β, cum)" },
  ],
  "dollar-dollarde": [{ excel: "DOLLARDE", syntax: "=DOLLARDE(frac_dollar, fraction)" }],
  "dollar-dollarfr": [{ excel: "DOLLARFR", syntax: "=DOLLARFR(decimal_dollar, fraction)" }],
  "discount-security": [
    { excel: "TBILLEQ", syntax: "=TBILLEQ(settle,maturity,discount)", parity: false, note: "T-bill bond-equivalent yield (actual/360; switches to the semiannual bond-equivalent formula past 182 days, per Excel). Confirmed against real Excel." },
    { excel: "TBILLPRICE", syntax: "=TBILLPRICE(settle,maturity,discount)", parity: false, note: "T-bill price per $100 face (actual/360). Confirmed against real Excel." },
    { excel: "TBILLYIELD", syntax: "=TBILLYIELD(settle,maturity,pr)", parity: false, note: "T-bill money-market yield from price (actual/360). Confirmed against real Excel." },
    { excel: "DISC", syntax: "=DISC(settle,maturity,pr,redemption,[basis])", parity: false, note: "basis 1 (actual/actual) is approximated as ÷365.25" },
    { excel: "PRICEDISC", syntax: "=PRICEDISC(settle,maturity,discount,redemption,basis)", parity: false, note: "Price of a discounted security per redemption. Bases: 0/4 = 30/360, 1/2 = actual/360, 3 = actual/365." },
    { excel: "YIELDDISC", syntax: "=YIELDDISC(settle,maturity,pr,redemption,basis)", parity: false, note: "Annual yield of a discounted security. Bases: 0/4 = 30/360, 1/2 = actual/360, 3 = actual/365." },
    { excel: "INTRATE", syntax: "=INTRATE(settle,maturity,invest,redemption,[basis])", parity: false, note: "basis 1 (actual/actual) is approximated as ÷365.25" },
    { excel: "RECEIVED", syntax: "=RECEIVED(settle,maturity,invest,discount,[basis])", parity: false, note: "basis 1 (actual/actual) is approximated as ÷365.25" },
    { excel: "PRICEMAT", syntax: "=PRICEMAT(settle,maturity,issue,rate,yld,basis)", parity: false, note: "Price of a security paying interest at maturity; bases 0/4 (30/360), 1 (actual/actual), 2 (actual/360), 3 (actual/365). Confirmed against real Excel." },
    { excel: "YIELDMAT", syntax: "=YIELDMAT(settle,maturity,issue,rate,pr,basis)", parity: false, note: "Annual yield of a security paying interest at maturity. Bases: 0/4 = 30/360, 1 = actual/actual, 2 = actual/360, 3 = actual/365." },
  ],
  "duration-duration": [{ excel: "DURATION", syntax: "=DURATION(settle,maturity,coupon,yld,freq,basis)", parity: true, note: "Macaulay duration in years; frequency 1/2/4, all five bases. Matches Excel's documented example." }],
  "duration-mduration": [{ excel: "MDURATION", syntax: "=MDURATION(settle,maturity,coupon,yld,freq,basis)", parity: true, note: "Modified Macaulay duration in years; frequency 1/2/4, all five bases." }],
  "f-test": [{ excel: "F.TEST", syntax: "=F.TEST(a, b)" }],
  "fisher-fisher": [{ excel: "FISHER", syntax: "=FISHER(x)", parity: true }],
  "fisher-fisherinv": [{ excel: "FISHERINV", syntax: "=FISHERINV(y)", parity: true }],
  "forecast": [
    { excel: "FORECAST.LINEAR", syntax: "=FORECAST.LINEAR(x, ys, xs)", parity: true, note: "X may be a scalar or a list; the result mirrors its shape." },
    { excel: "TREND", syntax: "=TREND(ys, xs, [new_xs])", parity: false, note: "Linear op. Simple linear regression; an unwired New Xs defaults to the Known Xs (fitted values), like Excel. Excel's const (force-intercept) and multiple-regression forms aren't modeled." },
    { excel: "GROWTH", syntax: "=GROWTH(ys, xs, new_xs)", parity: false, note: "Exponential op: the fit y = b·mˣ." },
  ],
  "ets-forecast": [
    { excel: "FORECAST.ETS", syntax: "=FORECAST.ETS(target_date, values, timeline, [seasonality])", parity: false, note: "Same additive Holt–Winters model; Solenoid fits α/β/γ by its own SSE search, so values are close to Excel's, not identical. Timeline must be equally spaced." },
    { excel: "FORECAST.ETS.CONFINT", syntax: "=FORECAST.ETS.CONFINT(target_date, values, timeline, [confidence_level])", parity: false, note: "z·σ·√h band" },
    { excel: "FORECAST.ETS.SEASONALITY", syntax: "=FORECAST.ETS.SEASONALITY(values, timeline)", parity: false, note: "Autocorrelation-peak detection; 0 when none" },
  ],
  "frequency": [{ excel: "FREQUENCY", syntax: "=FREQUENCY(data, bins)", parity: true }],
  "fvschedule": [{ excel: "FVSCHEDULE", syntax: "=FVSCHEDULE(pv, schedule)" }],
  "gcd-lcm": [{ excel: "GCD", syntax: "=GCD(a, b)", parity: true }],
  "lcm": [{ excel: "LCM", syntax: "=LCM(a, b)", parity: true }],
  "iferror": [{ excel: "IFERROR", syntax: "=IFERROR(v, fallback)", parity: true }],
  "ifna": [{ excel: "IFNA", syntax: "=IFNA(v, fallback)", parity: true }],
  "ifs": [{ excel: "IFS", syntax: "=IFS(c1, v1, c2, v2, ...)", parity: false, note: "Fixed 3 conditions; Excel is variadic" }],
  "payment-breakdown": [
    { excel: "IPMT", syntax: "=IPMT(rate, per, nper, pv)", parity: true },
    { excel: "PPMT", syntax: "=PPMT(rate, per, nper, pv)", parity: true },
    { excel: "CUMIPMT", syntax: "=CUMIPMT(rate, nper, pv, st, end, type)", parity: true },
    { excel: "CUMPRINC", syntax: "=CUMPRINC(rate, nper, pv, st, end, type)", parity: true },
  ],
  "fin-effective-rate": [
    { excel: "EFFECT", syntax: "=EFFECT(rate, npery)", parity: true, note: "One Equation node: wire nom + npery, read eff" },
    { excel: "NOMINAL", syntax: "=NOMINAL(eff_rate, npery)", parity: true, note: "Same node the other way: wire eff + npery, read nom" },
  ],
  "fin-compound-growth": [
    { excel: "PDURATION", syntax: "=PDURATION(rate, pv, fv)", parity: true, note: "The Compound Growth equation solving for nper" },
    { excel: "RRI", syntax: "=RRI(nper, pv, fv)", parity: true, note: "The Compound Growth equation solving for rate" },
  ],
  "irr": [{ excel: "IRR", syntax: "=IRR(cashflows)", parity: true }],
  "is-test": [
    { excel: "ISBLANK", syntax: "=ISBLANK(v)", parity: true },
    { excel: "ISERR", syntax: "=ISERR(v)", parity: false, note: "ISERR excludes #N/A; Solenoid's ISERROR catches all non-finite values" },
    { excel: "ISERROR", syntax: "=ISERROR(v)", parity: true },
    { excel: "ISLOGICAL", syntax: "=ISLOGICAL(v)", parity: true, note: "TRUE only for a real boolean (TRUE/FALSE), not 0/1 or \"TRUE\"; matches Excel's type check." },
    { excel: "ISBOOLEAN", syntax: "=ISBOOLEAN(v)", parity: false, note: "Solenoid's name for ISLOGICAL: the same test." },
    { excel: "ISNA", syntax: "=ISNA(v)", parity: false, note: "Returns 1 if value is N/A (NaN); use ISNA instead of ISERROR when testing only #N/A" },
    { excel: "ISNONTEXT", syntax: "=ISNONTEXT(v)", parity: false, note: "Returns 1 if value is not a string" },
    { excel: "ISNUMBER", syntax: "=ISNUMBER(v)", parity: true },
    { excel: "ISTEXT", syntax: "=ISTEXT(v)", parity: false, note: "Returns 1 if value is a string; wire from a Text input node" },
  ],
  "ispmt": [{ excel: "ISPMT", syntax: "=ISPMT(rate, per, nper, pv)" }],
  "linest": [
    { excel: "INTERCEPT", syntax: "=INTERCEPT(ys, xs)", parity: false, note: "Superseded by LINEST; use the Intercept output socket" },
    { excel: "LINEST", syntax: "=LINEST(ys, xs)", parity: false, note: "Returns [slope, intercept, r²] as a list; Excel returns a full 2×5 coefficient array" },
    { excel: "RSQ", syntax: "=RSQ(ys, xs)", parity: false, note: "Superseded by LINEST; use the R² output socket" },
    { excel: "SLOPE", syntax: "=SLOPE(ys, xs)", parity: false, note: "Superseded by LINEST; use the Slope output socket" },
    { excel: "LOGEST", syntax: "=LOGEST(ys, xs)", parity: false, note: "Exponential op: m, b, R² as three sockets; Excel returns a coefficient array" },
  ],
  "lambda-make": [{ excel: "LAMBDA", syntax: "=LAMBDA(param, ..., calculation)", parity: false, note: "LAMBDA node emits a function value for MAP/BYROW/REDUCE/MAKEARRAY; non-parameter variables become captured inputs (the LET/closure equivalent). No recursion (a self-reference is a graph cycle) and no lambdas of lambdas" }],
  "list-running": [{ excel: "SCAN", syntax: "=SCAN(init, array, LAMBDA(acc, value, ...))", parity: false, note: "Solenoid's Running covers the fixed ops in both window modes; the SCAN node runs a running fold with an arbitrary formula, and REDUCE gives just the final value. A Last N window in Excel is a dragged range formula like =AVERAGE(A1:A3) instead" }],
  "list-filter": [{ excel: "FILTER", syntax: "=FILTER(array, include)", parity: false, note: "Conditions live on the card (extensible AND/OR rows) instead of an include vector; filtering by a PARALLEL list is the SUMIFS node or Frame from Lists → Frame Filter" }],
  "list-groupby": [{ excel: "GROUPBY", syntax: "=GROUPBY(row_fields, values, function)", parity: false, note: "1D parallel-list version: keys + values lists; 2D range grouping not supported" }],
  "list-index": [{ excel: "INDEX", syntax: "=INDEX(array, row, [col])", parity: true, note: "Row or Column blank/0 = the whole axis, like Excel's INDEX(range, 0, col) whole-column / INDEX(range, row, 0) whole-row form" }],
  "list-randarray": [{ excel: "RANDARRAY", syntax: "=RANDARRAY(count,[min],[max],[integer])", parity: false, note: "1D list (Excel's rows×cols become a single Count); the Integer flag is supported; re-rolls on recalc, F9" }],
  "list-sequence": [{ excel: "SEQUENCE", syntax: "=SEQUENCE(rows, cols, start, step)", parity: false, note: "Solenoid's Range is 1D only; SEQUENCE can produce 2D arrays" }],
  "list-sort": [
    { excel: "SORT", syntax: "=SORT(array, sort_index, order)", parity: false, note: "Solenoid sorts 1D lists only; Excel can sort multi-column ranges" },
    { excel: "SORTBY", syntax: "=SORTBY(array, by_array)", parity: false, note: "Wire the Sort node's `by` input: reorders a 1-D array of ANY element type (position-only) by a parallel NUMERIC key list; text sort keys aren't supported yet" },
  ],
  "list-unique": [{ excel: "UNIQUE", syntax: "=UNIQUE(array)", parity: true }],
  "xstack": [
    { excel: "VSTACK", syntax: "=VSTACK(array1, array2, ...)", parity: true, note: "N-ary; ragged inputs pad with #N/A like Excel. A bare list counts as ONE ROW" },
    { excel: "HSTACK", syntax: "=HSTACK(array1, array2, ...)", parity: true, note: "N-ary; ragged inputs pad with #N/A like Excel. A bare list counts as ONE ROW" },
    { excel: "XSTACK", syntax: "=XSTACK(axis, array1, array2, ...)", parity: false, note: "Solenoid: one function, axis first, \"v\" or \"h\"" },
  ],
  // Keys MUST track the catalog types; a drift test catches stale ones.
  "bool-and": [{ excel: "AND", syntax: "=AND(a, b, ...)", parity: true }],
  "if": [{ excel: "IF", syntax: "=IF(cond, a, b)", parity: true }],
  "not": [{ excel: "NOT", syntax: "=NOT(a)", parity: true }],
  "bool-or": [{ excel: "OR", syntax: "=OR(a, b, ...)", parity: true }],
  "bool-xor": [{ excel: "XOR", syntax: "=XOR(a, b, ...)", parity: true }],
  "lookup-xlookup": [{ excel: "XLOOKUP", syntax: "=XLOOKUP(x, lookup, return)", parity: true }],
  "lookup-xmatch": [{ excel: "XMATCH", syntax: "=XMATCH(x, array, [match_mode], [search_mode])", parity: false, note: "Match modes 0 / 1 / -1 and search modes 1 (first) / -1 (last); wildcard (2) and binary search (±2) not supported" }],
  "make-array": [{ excel: "MAKEARRAY", syntax: "=MAKEARRAY(rows, cols, LAMBDA(row, col, ...))", parity: false, note: "MAKEARRAY node builds a grid from its own formula of (row, col), or a wired LAMBDA value" }],
  "map-table": [{ excel: "MAP", syntax: "=MAP(array1, [array2, ...], LAMBDA(value, ...))", parity: false, note: "MAP node zips up to three same-shape arrays through its own formula (value, value2, value3; a 1×1 broadcasts) or a wired LAMBDA value; Excel takes any number of arrays" }],
  "matdet-mdeterm": [{ excel: "MDETERM", syntax: "=MDETERM(array)", parity: false, note: "Square matrices only; uses LU decomposition with partial pivoting" }],
  "matdet-minverse": [{ excel: "MINVERSE", syntax: "=MINVERSE(array)", parity: false, note: "Square matrices only; returns null for singular matrices" }],
  "math-abs": [{ excel: "ABS", syntax: "=ABS(x)", parity: true }],
  "math-acos": [{ excel: "ACOS", syntax: "=ACOS(x)", parity: true }],
  "math-acosh": [{ excel: "ACOSH", syntax: "=ACOSH(x)", parity: true }],
  "math-acot": [{ excel: "ACOT", syntax: "=ACOT(x)", parity: true }],
  "math-acoth": [{ excel: "ACOTH", syntax: "=ACOTH(x)", parity: true }],
  "math-asin": [{ excel: "ASIN", syntax: "=ASIN(x)", parity: true }],
  "math-asinh": [{ excel: "ASINH", syntax: "=ASINH(x)", parity: true }],
  "math-atan": [{ excel: "ATAN", syntax: "=ATAN(x)", parity: true }],
  "math-atanh": [{ excel: "ATANH", syntax: "=ATANH(x)", parity: true }],
  "math-cos": [{ excel: "COS", syntax: "=COS(x)", parity: true }],
  "math-cosh": [{ excel: "COSH", syntax: "=COSH(x)", parity: true }],
  "math-cot": [{ excel: "COT", syntax: "=COT(x)", parity: true }],
  "math-coth": [{ excel: "COTH", syntax: "=COTH(x)", parity: true }],
  "math-csc": [{ excel: "CSC", syntax: "=CSC(x)", parity: true }],
  "math-csch": [{ excel: "CSCH", syntax: "=CSCH(x)", parity: true }],
  "math-erf": [
    { excel: "ERF", syntax: "=ERF(x)", parity: true },
    { excel: "ERF.PRECISE", syntax: "=ERF.PRECISE(x)", parity: true, note: "Same as ERF in Solenoid" },
  ],
  "math-erfc": [
    { excel: "ERFC", syntax: "=ERFC(x)", parity: true },
    { excel: "ERFC.PRECISE", syntax: "=ERFC.PRECISE(x)", parity: true, note: "Same as ERFC in Solenoid" },
  ],
  "math-even": [{ excel: "EVEN", syntax: "=EVEN(x)", parity: true }],
  "math-exp": [{ excel: "EXP", syntax: "=EXP(x)", parity: true }],
  "math-ceiling": [
    { excel: "CEILING.MATH", syntax: "=CEILING.MATH(x, sig)", parity: true, note: "Rounds toward +∞ to a multiple (the Multiple input); defaults to 1" },
    { excel: "CEILING", syntax: "=CEILING(x, significance)", parity: false, note: "Rounds toward +∞ like CEILING.MATH; Excel's CEILING rounds away from zero for negatives" },
  ],
  "math-floor": [
    { excel: "FLOOR.MATH", syntax: "=FLOOR.MATH(x, sig)", parity: true, note: "Rounds toward −∞ to a multiple (the Multiple input); defaults to 1" },
    { excel: "FLOOR", syntax: "=FLOOR(x, significance)", parity: false, note: "Rounds toward −∞ like FLOOR.MATH; Excel's FLOOR rounds toward zero for negatives" },
  ],
  "math-gamma": [{ excel: "GAMMA", syntax: "=GAMMA(x)" }],
  "math-gammaln": [
    { excel: "GAMMALN", syntax: "=GAMMALN(x)" },
    { excel: "GAMMALN.PRECISE", syntax: "=GAMMALN.PRECISE(x)" },
  ],
  "math-int": [{ excel: "INT", syntax: "=INT(x)", parity: true }],
  "iseven-isodd": [{ excel: "ISEVEN", syntax: "=ISEVEN(x)", parity: true, note: "Emits a logical (TRUE/FALSE), broadcasts over a list" }],
  "isodd": [{ excel: "ISODD", syntax: "=ISODD(x)", parity: true, note: "Emits a logical (TRUE/FALSE), broadcasts over a list" }],
  "math-log": [{ excel: "LN", syntax: "=LN(x)", parity: true }],
  "math-log10": [{ excel: "LOG10", syntax: "=LOG10(x)", parity: true }],
  "math-mround": [{ excel: "MROUND", syntax: "=MROUND(x, multiple)", parity: true }],
  "math-odd": [{ excel: "ODD", syntax: "=ODD(x)", parity: true }],
  "math-sec": [{ excel: "SEC", syntax: "=SEC(x)", parity: true }],
  "math-sech": [{ excel: "SECH", syntax: "=SECH(x)", parity: true }],
  "math-sign": [{ excel: "SIGN", syntax: "=SIGN(x)", parity: true }],
  "math-sin": [{ excel: "SIN", syntax: "=SIN(x)", parity: true }],
  "math-sinh": [{ excel: "SINH", syntax: "=SINH(x)", parity: true }],
  "math-sqrt": [{ excel: "SQRT", syntax: "=SQRT(x)", parity: true }],
  "math-sqrtpi": [{ excel: "SQRTPI", syntax: "=SQRTPI(x)", parity: true }],
  "math-tan": [{ excel: "TAN", syntax: "=TAN(x)", parity: true }],
  "math-tanh": [{ excel: "TANH", syntax: "=TANH(x)", parity: true }],
  "math-trunc": [{ excel: "TRUNC", syntax: "=TRUNC(x)", parity: true }],
  "mirr": [{ excel: "MIRR", syntax: "=MIRR(flows, fin_rate, reinv_rate)", parity: true }],
  "mode": [
    { excel: "MODE.SNGL", syntax: "=MODE.SNGL(range)" },
    { excel: "MODE.MULT", syntax: "=MODE.MULT(range)" },
  ],
  "multinomial": [{ excel: "MULTINOMIAL", syntax: "=MULTINOMIAL(n1, n2, ...)", parity: true }],
  "na": [{ excel: "NA", syntax: "=NA()", parity: true }],
  "npv": [{ excel: "NPV", syntax: "=NPV(rate, v1, v2, ...)", parity: true }],
  "nth-large": [{ excel: "LARGE", syntax: "=LARGE(array, k)", parity: true }],
  "nth-small": [{ excel: "SMALL", syntax: "=SMALL(array, k)", parity: true }],

  "prob": [{ excel: "PROB", syntax: "=PROB(range, prob, lo, hi)" }],
  "randbetween": [
    { excel: "RAND", syntax: "=RAND()", parity: true },
    { excel: "RANDBETWEEN", syntax: "=RANDBETWEEN(bot, top)", parity: false, note: "Solenoid returns a float; Excel returns an integer" },
  ],
  "rank-avg": [{ excel: "RANK.AVG", syntax: "=RANK.AVG(x, array)", parity: true }],
  "rank-eq": [{ excel: "RANK.EQ", syntax: "=RANK.EQ(x, array)", parity: true }],

  "reduce-avedev": [{ excel: "AVEDEV", syntax: "=AVEDEV(range)", parity: true }],
  "reduce-avg": [
    { excel: "AVERAGE", syntax: "=AVERAGE(range)", parity: true },
    { excel: "AVERAGEA", syntax: "=AVERAGEA(range)", parity: false, note: "AVERAGEA counts text as 0; Solenoid is numbers-only" },
  ],
  "reduce-count": [
    { excel: "COUNT", syntax: "=COUNT(range)", parity: true },
    { excel: "COUNTA", syntax: "=COUNTA(range)", parity: false, note: "COUNTA counts non-empty cells; Solenoid is numbers-only" },
  ],
  "reduce-countblank": [{ excel: "COUNTBLANK", syntax: "=COUNTBLANK(range)", parity: true }],
  "reduce-devsq": [{ excel: "DEVSQ", syntax: "=DEVSQ(range)", parity: true }],
  "reduce-geomean": [{ excel: "GEOMEAN", syntax: "=GEOMEAN(range)", parity: true }],
  "reduce-harmean": [{ excel: "HARMEAN", syntax: "=HARMEAN(range)", parity: true }],
  "reduce-kurt": [{ excel: "KURT", syntax: "=KURT(range)", parity: true }],
  "reduce-lambda": [{ excel: "REDUCE", syntax: "=REDUCE(init, array, LAMBDA(acc, value, ...))", parity: false, note: "REDUCE node folds with its own formula of (acc, value), or a wired LAMBDA value" }],
  "scan-lambda": [{ excel: "SCAN", syntax: "=SCAN(init, array, LAMBDA(acc, value, ...))", parity: false, note: "SCAN node folds like REDUCE but emits every running accumulator, same shape as the input, with its own formula of (acc, value) or a wired LAMBDA value" }],
  "reduce-max": [
    { excel: "MAX", syntax: "=MAX(range)", parity: true },
    { excel: "MAXA", syntax: "=MAXA(range)", parity: false, note: "MAXA counts text as 0; Solenoid is numbers-only" },
  ],
  "reduce-median": [{ excel: "MEDIAN", syntax: "=MEDIAN(range)", parity: true }],
  "reduce-min": [
    { excel: "MIN", syntax: "=MIN(range)", parity: true },
    { excel: "MINA", syntax: "=MINA(range)", parity: false, note: "MINA counts text as 0; Solenoid is numbers-only" },
  ],
  "reduce-product": [{ excel: "PRODUCT", syntax: "=PRODUCT(n1, n2, ...)", parity: false, note: "Solenoid takes a single list input; build list first with List node" }],
  "reduce-skew": [{ excel: "SKEW", syntax: "=SKEW(range)", parity: true }],
  "reduce-skew_p": [{ excel: "SKEW.P", syntax: "=SKEW.P(range)", parity: true }],
  "reduce-stdev": [
    { excel: "STDEV.S", syntax: "=STDEV.S(range)", parity: true },
    { excel: "STDEVA", syntax: "=STDEVA(range)", parity: false, note: "STDEVA counts text as 0; Solenoid is numbers-only" },
  ],
  "reduce-stdev_p": [
    { excel: "STDEV.P", syntax: "=STDEV.P(range)", parity: true },
    { excel: "STDEVPA", syntax: "=STDEVPA(range)", parity: false, note: "STDEVPA counts text as 0; Solenoid is numbers-only" },
  ],
  "reduce-sum": [{ excel: "SUM", syntax: "=SUM(range)", parity: true }],
  "reduce-sumsq": [{ excel: "SUMSQ", syntax: "=SUMSQ(n1, n2, ...)", parity: false, note: "Solenoid takes a list input; build list first" }],
  "reduce-var_p": [
    { excel: "VAR.P", syntax: "=VAR.P(range)", parity: true },
    { excel: "VARPA", syntax: "=VARPA(range)", parity: false, note: "VARPA counts text as 0; Solenoid is numbers-only" },
  ],
  "reduce-var_s": [
    { excel: "VAR.S", syntax: "=VAR.S(range)", parity: true },
    { excel: "VARA", syntax: "=VARA(range)", parity: false, note: "VARA counts text as 0; Solenoid is numbers-only" },
  ],
  "regex": [
    { excel: "REGEXTEST", syntax: "=REGEXTEST(text, pattern)", parity: false, note: "Returns 1/0; use Regex node with REGEXTEST op" },
    { excel: "REGEXEXTRACT", syntax: "=REGEXEXTRACT(text, pattern, [return_mode])", parity: false, note: "Regex node ops: REGEXEXTRACT (first), (all), (groups); Excel's return_mode 0/1/2" },
    { excel: "REGEXREPLACE", syntax: "=REGEXREPLACE(text, pattern, replacement, [occurrence])", parity: false, note: "Regex node REGEXREPLACE op; blank/0 Occurrence replaces all, n replaces only the nth" },
  ],
  "regression-steyx": [{ excel: "STEYX", syntax: "=STEYX(ys, xs)", parity: true }],
  "reshape-tocol": [{ excel: "TOCOL", syntax: "=TOCOL(array)", parity: false, note: "ignore_empty and scan_by_column flags not supported" }],
  "reshape-torow": [{ excel: "TOROW", syntax: "=TOROW(array)", parity: false, note: "ignore_empty flag not supported" }],
  "reshape-wrapcols": [{ excel: "WRAPCOLS", syntax: "=WRAPCOLS(vector, wrap_count, [pad_with])", parity: true, note: "Unwired Fill pads with #N/A (Excel's default); wire Fill for a custom pad_with" }],
  "reshape-wraprows": [{ excel: "WRAPROWS", syntax: "=WRAPROWS(vector, wrap_count, [pad_with])", parity: true, note: "Unwired Fill pads with #N/A (Excel's default); wire Fill for a custom pad_with" }],
  "roman-arabic-arabic": [{ excel: "ARABIC", syntax: "=ARABIC(text)", parity: false, note: "Roman numeral string → integer" }],
  "roman-arabic-roman": [{ excel: "ROMAN", syntax: "=ROMAN(n)", parity: false, note: "Integer (1–3999) → Roman numeral string" }],
  "roundn-dir": [{ excel: "ROUNDUP", syntax: "=ROUNDUP(x, digits)", parity: true }],
  "roundn-down": [{ excel: "ROUNDDOWN", syntax: "=ROUNDDOWN(x, digits)", parity: true }],
  "roundn-round": [{ excel: "ROUND", syntax: "=ROUND(x, digits)", parity: true }],

  "seriessum": [{ excel: "SERIESSUM", syntax: "=SERIESSUM(x, n, m, coef)", parity: true }],
  "sp-sumproduct": [{ excel: "SUMPRODUCT", syntax: "=SUMPRODUCT(a, b)", parity: false, note: "Solenoid takes exactly two list inputs, no 3+ arrays" }],
  "sp-sumx2my2": [{ excel: "SUMX2MY2", syntax: "=SUMX2MY2(x, y)", parity: true }],
  "sp-sumx2py2": [{ excel: "SUMX2PY2", syntax: "=SUMX2PY2(x, y)", parity: true }],
  "sp-sumxmy2": [{ excel: "SUMXMY2", syntax: "=SUMXMY2(x, y)", parity: true }],
  "stat-percentile": [
    { excel: "PERCENTILE.EXC", syntax: "=PERCENTILE.EXC(array, k)", parity: true },
    { excel: "PERCENTILE.INC", syntax: "=PERCENTILE.INC(array, k)", parity: true },
  ],
  "stat-percentrank": [
    { excel: "PERCENTRANK.EXC", syntax: "=PERCENTRANK.EXC(array, x)", parity: true },
    { excel: "PERCENTRANK.INC", syntax: "=PERCENTRANK.INC(array, x)", parity: true },
  ],
  "stat-quartile": [
    { excel: "QUARTILE.EXC", syntax: "=QUARTILE.EXC(array, q)", parity: true },
    { excel: "QUARTILE.INC", syntax: "=QUARTILE.INC(array, q)", parity: true },
  ],
  "stat-standardize": [{ excel: "STANDARDIZE", syntax: "=STANDARDIZE(x, μ, σ)", parity: true }],
  "switch": [{ excel: "SWITCH", syntax: "=SWITCH(expr, w1, t1, ...)", parity: false, note: "Fixed 3 cases; Excel is variadic" }],
  // All three leaves ARE T.TEST (Excel splits by its `type` argument), and all three must
  // say so or the parity measurement reads the other two as Solenoid-native.
  "t-test-paired": [{ excel: "T.TEST", syntax: "=T.TEST(a, b, tails, 1)", parity: false, note: "This leaf is type 1 (paired); 2-tailed only" }],
  "t-test-equal-var": [{ excel: "T.TEST", syntax: "=T.TEST(a, b, tails, 2)", parity: false, note: "This leaf is type 2 (pooled variance); 2-tailed only, for 1-tailed divide result by 2" }],
  "t-test-unequal-var": [{ excel: "T.TEST", syntax: "=T.TEST(a, b, tails, 3)", parity: false, note: "This leaf is type 3 (Welch); 2-tailed only" }],
  "table-info": [
    { excel: "COLUMNS", syntax: "=COLUMNS(array)", parity: true, note: "Counts a matrix's columns or a list's length, treating a list as one row" },
    { excel: "ROWS", syntax: "=ROWS(array)", parity: true, note: "Counts a matrix's rows; a list is one row, so ROWS of a list is 1" },
  ],
  "table-mult": [{ excel: "MMULT", syntax: "=MMULT(a, b)", parity: false, note: "A columns must equal B rows" }],
  "table-transpose": [{ excel: "TRANSPOSE", syntax: "=TRANSPOSE(array)", parity: false }],
  "table-unit": [{ excel: "MUNIT", syntax: "=MUNIT(n)", parity: false }],
  "tblsel-choosecols": [{ excel: "CHOOSECOLS", syntax: "=CHOOSECOLS(array, col1, col2, ...)", parity: false, note: "Takes a list of indices; negative indices count from end" }],
  "tblsel-chooserows": [{ excel: "CHOOSEROWS", syntax: "=CHOOSEROWS(array, row1, row2, ...)", parity: false, note: "Takes a list of indices; negative indices count from end" }],
  "text-after-before-after": [{ excel: "TEXTAFTER", syntax: "=TEXTAFTER(text, delimiter)", parity: false, note: "First occurrence only; instance_num and match_mode not supported" }],
  "text-after-before-before": [{ excel: "TEXTBEFORE", syntax: "=TEXTBEFORE(text, delimiter)", parity: false, note: "First occurrence only; instance_num and match_mode not supported" }],
  "text-clean": [{ excel: "CLEAN", syntax: "=CLEAN(text)", parity: false }],
  "text-concat": [
    { excel: "CONCAT", syntax: "=CONCAT(text1, text2, ...)", parity: false, note: "Fixed 4 inputs; chain Concat nodes for more" },
    { excel: "CONCATENATE", syntax: "=CONCATENATE(text1, ...)", parity: false, note: "Fixed 4 inputs; chain Concat nodes for more" },
  ],
  "text-dollar": [{ excel: "DOLLAR", syntax: "=DOLLAR(number)", parity: false, note: "Formats as \"$1,234.56\"; optional decimals input" }],
  "text-exact": [{ excel: "EXACT", syntax: "=EXACT(text1, text2)", parity: false }],
  "text-find-find": [
    { excel: "FIND", syntax: "=FIND(find_text, within)", parity: false },
  ],
  "text-find-search": [
    { excel: "SEARCH", syntax: "=SEARCH(find_text, within)", parity: false },
  ],
  "text-fixed": [{ excel: "FIXED", syntax: "=FIXED(number, decimals)", parity: false, note: "Use TEXT node with \"0.00\" format" }],
  "text-join": [{ excel: "TEXTJOIN", syntax: "=TEXTJOIN(delim, ignore, ...)", parity: false, note: "Takes a strlist input; wire from TEXTSPLIT or a Text Input list" }],
  "text-left": [
    { excel: "LEFT", syntax: "=LEFT(text, chars)", parity: false },
  ],
  "text-len": [
    { excel: "LEN", syntax: "=LEN(text)", parity: false },
  ],
  "text-lower": [{ excel: "LOWER", syntax: "=LOWER(text)", parity: false }],
  "text-mid": [
    { excel: "MID", syntax: "=MID(text, start, chars)", parity: false },
  ],
  // TEXT / VALUE / VALUETOTEXT live on Cast; their dedicated nodes are load-only.
  "cast": [
    { excel: "TEXT", syntax: "=TEXT(value, format)", parity: false, note: "Cast to Text with a format; simplified formats: \"\", \"0\", \"0.00\", \"0.00%\"; date patterns (YYYY-MM-DD) for date sources" },
    { excel: "VALUE", syntax: "=VALUE(text)", parity: false, note: "Cast to Number" },
    { excel: "VALUETOTEXT", syntax: "=VALUETOTEXT(value)", parity: false, note: "Cast to Text with an empty format; default string conversion" },
  ],
  "text-numbervalue": [{ excel: "NUMBERVALUE", syntax: "=NUMBERVALUE(text)", parity: false, note: "Custom decimal/group separators; for plain parsing use Cast to Number" }],
  "text-proper": [{ excel: "PROPER", syntax: "=PROPER(text)", parity: false }],
  "text-replace": [
    { excel: "REPLACE", syntax: "=REPLACE(text, start, n, new)", parity: false },
  ],
  "text-rept": [{ excel: "REPT", syntax: "=REPT(text, n)", parity: false }],
  "text-right": [
    { excel: "RIGHT", syntax: "=RIGHT(text, chars)", parity: false },
  ],
  "text-split": [
    { excel: "TEXTSPLIT", syntax: "=TEXTSPLIT(text, delim)", parity: false, note: "Outputs a strlist; row/col delimiter pair not supported" },
    { excel: "TEXTSPLIT", syntax: "=TEXTSPLIT(text, delim)", parity: false, note: "Row/col delimiter pair not supported; outputs a strlist" },
  ],
  "text-substitute": [{ excel: "SUBSTITUTE", syntax: "=SUBSTITUTE(text, old, new, [instance])", parity: true }],
  "text-trim": [{ excel: "TRIM", syntax: "=TRIM(text)", parity: false }],
  "text-upper": [{ excel: "UPPER", syntax: "=UPPER(text)", parity: false }],
  "time-value": [{ excel: "TIMEVALUE", syntax: "=TIMEVALUE(time_text)", parity: false, note: "Parses HH:MM:SS format" }],
  "trimmean": [{ excel: "TRIMMEAN", syntax: "=TRIMMEAN(range, pct)", parity: true }],
  "sumifs": [
    { excel: "SUMIFS", syntax: "=SUMIFS(sum_range, criteria_range1, criteria1, ...)", parity: true, note: "Takes one frame: ranges are named columns; criteria are op + value rows instead of criteria strings like \">10\"" },
    { excel: "COUNTIFS", syntax: "=COUNTIFS(criteria_range1, criteria1, ...)", parity: true },
    { excel: "COUNTIF", syntax: "=COUNTIF(range, criteria)", parity: true, note: "The singular form: one criteria row on this node" },
    { excel: "AVERAGEIFS", syntax: "=AVERAGEIFS(average_range, criteria_range1, criteria1, ...)", parity: true },
    { excel: "AVERAGEIF", syntax: "=AVERAGEIF(range, criteria, [average_range])", parity: true, note: "The singular form: one criteria row on this node; Values names the average_range" },
    { excel: "MINIFS", syntax: "=MINIFS(min_range, criteria_range1, criteria1, ...)", parity: true },
    { excel: "MAXIFS", syntax: "=MAXIFS(max_range, criteria_range1, criteria1, ...)", parity: true },
  ],
  "takedrop": [{ excel: "TAKE", syntax: "=TAKE(array, rows, [cols])", parity: true, note: "One rank-preserving card: a list takes one count, a table takes rows and cols; negative counts from the end; 0 stands in for an omitted argument" }],
  "takedrop-drop": [{ excel: "DROP", syntax: "=DROP(array, rows, [cols])", parity: true, note: "One rank-preserving card: a list drops one count, a table drops rows and cols; negative counts from the end; 0 stands in for an omitted argument" }],
  "table-expand": [{ excel: "EXPAND", syntax: "=EXPAND(array, rows, [cols], [pad_with])", parity: false, note: "Omitted Fill pads with first-class null, not Excel's #N/A; the author override, so wire the NA node for Excel's form" }],
  "tvm": [
    { excel: "PMT", syntax: "=PMT(rate, nper, pv)", parity: true, note: "One acausal TVM node: leave pmt unwired and it solves" },
    { excel: "PV", syntax: "=PV(rate, nper, pmt, fv)", parity: true, note: "Leave pv unwired" },
    { excel: "FV", syntax: "=FV(rate, nper, pmt, pv)", parity: true, note: "Leave fv unwired" },
    { excel: "NPER", syntax: "=NPER(rate, pmt, pv)", parity: true, note: "Leave nper unwired" },
    { excel: "RATE", syntax: "=RATE(nper, pmt, pv)", parity: true, note: "Leave rate unwired; no guess needed" },
  ],
  "twomath-atan2": [{ excel: "ATAN2", syntax: "=ATAN2(x, y)", parity: true }],
  "twomath-delta": [{ excel: "DELTA", syntax: "=DELTA(a, b)", parity: true }],
  "twomath-gestep": [{ excel: "GESTEP", syntax: "=GESTEP(a, step)", parity: true }],
  "twomath-log": [{ excel: "LOG", syntax: "=LOG(x, base)", parity: true }],
  "url-encode": [{ excel: "ENCODEURL", syntax: "=ENCODEURL(text)", parity: false, note: "Percent-encodes via JS encodeURIComponent; Excel additionally encodes ! ' ( ) *, which this leaves literal. DECODEURL passes a malformed escape through unchanged." }],
  "vdb": [{ excel: "VDB", syntax: "=VDB(cost,salv,life,start,end,[factor])", note: "factor defaults to 2 (DDB); no_switch flag not exposed" }],
  "xirr": [{ excel: "XIRR", syntax: "=XIRR(flows, dates)", parity: false, note: "Dates as serials (wire from date nodes); guess parameter not supported" }],
  "xnpv": [{ excel: "XNPV", syntax: "=XNPV(rate, flows, dates)", parity: false, note: "Date-based NPV; dates are Solenoid serials (wire from date nodes). Uneven flow/date lists are truncated to the shorter." }],
  "z-test": [{ excel: "Z.TEST", syntax: "=Z.TEST(array, μ, σ)", parity: false, note: "σ is optional; if omitted uses sample stdev, matching Excel's behavior" }],
};

export interface ExcelGapRow {
  excel: string;
  syntax: string;
  category: string;
  oos?: boolean;        // the concept has no place here (cell refs, OLAP, locale byte semantics)
  superseded?: boolean; // a modern replacement covers it; the name is blocked on the formula surface (LEGACY_ALIASES)
  note?: string;
}

/** Excel functions with no Solenoid node; the reference drops any entry whose name later
 *  becomes node-backed. */
export const EXCEL_GAP: ExcelGapRow[] = [
  { excel: "SUBTOTAL", syntax: "=SUBTOTAL(fn, range)", category: "Math & Trig", superseded: true, note: "Use SUM or the matching aggregate; the hidden-row variants (101-111) are a cell-grid concept." },
  { excel: "AGGREGATE", syntax: "=AGGREGATE(fn, opts, range)", category: "Math & Trig", superseded: true, note: "Use the matching aggregate; the ignore-errors and hidden-rows options are cell-grid concepts." },
  { excel: "CEILING.PRECISE", syntax: "=CEILING.PRECISE(x, sig)", category: "Math & Trig", superseded: true, note: "Use CEILING.MATH; PRECISE differs only in ignoring the significance's sign." },
  { excel: "FLOOR.PRECISE", syntax: "=FLOOR.PRECISE(x, sig)", category: "Math & Trig", superseded: true, note: "Use FLOOR.MATH; PRECISE differs only in ignoring the significance's sign." },
  { excel: "ISO.CEILING", syntax: "=ISO.CEILING(x, sig)", category: "Math & Trig", superseded: true, note: "Use CEILING.MATH; ISO.CEILING is CEILING.PRECISE under its ISO name." },
  // The *IFS family + singular COUNTIF/AVERAGEIF are node-backed (sumifs node) → NODE_EXCEL.
  // Only SUMIF stays a gap: it is blocked (Formula.js mis-summed a numeric-string range).
  { excel: "SUMIF", syntax: "=SUMIF(range, crit)", category: "Math & Trig", superseded: true, note: "Use SUMIFS." },
  { excel: "ADDRESS", syntax: "=ADDRESS(row, col)", category: "Lookup & Reference", oos: true, note: "Returns a cell reference as text." },
  { excel: "AREAS", syntax: "=AREAS(reference)", category: "Lookup & Reference", oos: true, note: "Counts the areas in a cell reference." },
  { excel: "COLUMN", syntax: "=COLUMN(reference)", category: "Lookup & Reference", oos: true, note: "Returns a cell reference's column number." },
  { excel: "FORMULATEXT", syntax: "=FORMULATEXT(reference)", category: "Lookup & Reference", oos: true, note: "Returns a cell's formula as text." },
  { excel: "GETPIVOTDATA", syntax: "=GETPIVOTDATA(field, pivot, ...)", category: "Lookup & Reference", oos: true, note: "Extracts a value from a PivotTable report." },
  { excel: "HLOOKUP", syntax: "=HLOOKUP(x, table, row)", category: "Lookup & Reference", superseded: true, note: "Use XLOOKUP." },
  { excel: "HYPERLINK", syntax: "=HYPERLINK(url, text)", category: "Lookup & Reference", oos: true, note: "Creates a clickable link in a cell." },
  { excel: "INDIRECT", syntax: "=INDIRECT(ref_text)", category: "Lookup & Reference", oos: true, note: "Evaluates a text string as a cell reference." },
  { excel: "LOOKUP", syntax: "=LOOKUP(x, lookup_vector, result)", category: "Lookup & Reference", superseded: true, note: "Use XLOOKUP." },
  { excel: "MATCH", syntax: "=MATCH(x, array, type)", category: "Lookup & Reference", superseded: true, note: "Use XMATCH." },
  { excel: "OFFSET", syntax: "=OFFSET(ref, rows, cols)", category: "Lookup & Reference", oos: true, note: "Returns a reference offset from a cell." },
  { excel: "ROW", syntax: "=ROW(reference)", category: "Lookup & Reference", oos: true, note: "Returns a cell reference's row number." },
  { excel: "RTD", syntax: "=RTD(prog_id, server, ...)", category: "Lookup & Reference", oos: true, note: "Pulls real-time data from a COM server." },
  { excel: "VLOOKUP", syntax: "=VLOOKUP(x, table, col)", category: "Lookup & Reference", superseded: true, note: "Use XLOOKUP." },
  { excel: "CELL", syntax: "=CELL(info_type, ref)", category: "Info", oos: true, note: "Returns a cell's metadata." },
  { excel: "N", syntax: "=N(value)", category: "Info", oos: true, note: "Coerces a value to a number; sockets are typed, so there is nothing to coerce blind" },
  { excel: "T", syntax: "=T(value)", category: "Info", oos: true, note: "Returns text or empty by inspecting an untyped cell; sockets are typed" },
  { excel: "TYPE", syntax: "=TYPE(value)", category: "Info", oos: true, note: "Excel's type enum for an untyped cell; a socket already declares its type" },
  { excel: "ERROR.TYPE", syntax: "=ERROR.TYPE(error_val)", category: "Info", oos: true, note: "Excel error-type enum; no cell-error model in a node graph" },
  { excel: "INFO", syntax: "=INFO(type_text)", category: "Info", oos: true, note: "Reports environment information." },
  { excel: "ISFORMULA", syntax: "=ISFORMULA(ref)", category: "Info", oos: true, note: "Tests whether a cell holds a formula." },
  { excel: "ISREF", syntax: "=ISREF(v)", category: "Info", oos: true, note: "Tests whether a value is a cell reference." },
  { excel: "SHEET", syntax: "=SHEET(value)", category: "Info", oos: true, note: "Returns a sheet's index number." },
  { excel: "SHEETS", syntax: "=SHEETS(reference)", category: "Info", oos: true, note: "Counts the sheets in a reference." },
  { excel: "FILTERXML", syntax: "=FILTERXML(xml, xpath)", category: "Web & Cube", oos: true, note: "Extracts XML content by XPath." },
  { excel: "WEBSERVICE", syntax: "=WEBSERVICE(url)", category: "Web & Cube", oos: true, note: "Fetches a URL from inside a formula; fetching is a node's job." },
  { excel: "CUBEKPIMEMBER", syntax: "=CUBEKPIMEMBER(...)", category: "Web & Cube", oos: true, note: "Queries an OLAP cube." },
  { excel: "CUBEMEMBER", syntax: "=CUBEMEMBER(connection, expr)", category: "Web & Cube", oos: true, note: "Queries an OLAP cube." },
  { excel: "CUBEMEMBERPROPERTY", syntax: "=CUBEMEMBERPROPERTY(...)", category: "Web & Cube", oos: true, note: "Queries an OLAP cube." },
  { excel: "CUBERANKEDMEMBER", syntax: "=CUBERANKEDMEMBER(...)", category: "Web & Cube", oos: true, note: "Queries an OLAP cube." },
  { excel: "CUBESET", syntax: "=CUBESET(connection, set_expr)", category: "Web & Cube", oos: true, note: "Queries an OLAP cube." },
  { excel: "CUBESETCOUNT", syntax: "=CUBESETCOUNT(set)", category: "Web & Cube", oos: true, note: "Queries an OLAP cube." },
  { excel: "CUBEVALUE", syntax: "=CUBEVALUE(connection, ...)", category: "Web & Cube", oos: true, note: "Queries an OLAP cube." },
  { excel: "LENB", syntax: "=LENB(text)", category: "Text", oos: true, note: "Byte-counted twin for double-byte locales; Solenoid counts characters, so it is LEN." },
  { excel: "LEFTB", syntax: "=LEFTB(text, bytes)", category: "Text", oos: true, note: "Byte-counted twin for double-byte locales; Solenoid counts characters, so it is LEFT." },
  { excel: "MIDB", syntax: "=MIDB(text, start, bytes)", category: "Text", oos: true, note: "Byte-counted twin for double-byte locales; Solenoid counts characters, so it is MID." },
  { excel: "RIGHTB", syntax: "=RIGHTB(text, bytes)", category: "Text", oos: true, note: "Byte-counted twin for double-byte locales; Solenoid counts characters, so it is RIGHT." },
  { excel: "FINDB", syntax: "=FINDB(find_text, within)", category: "Text", oos: true, note: "Byte-counted twin for double-byte locales; Solenoid counts characters, so it is FIND." },
  { excel: "SEARCHB", syntax: "=SEARCHB(find_text, within)", category: "Text", oos: true, note: "Byte-counted twin for double-byte locales; Solenoid counts characters, so it is SEARCH." },
  { excel: "REPLACEB", syntax: "=REPLACEB(text, start, bytes, new)", category: "Text", oos: true, note: "Byte-counted twin for double-byte locales; Solenoid counts characters, so it is REPLACE." },
  { excel: "ASC", syntax: "=ASC(text)", category: "Text", oos: true, note: "Converts East Asian full-width characters to half-width." },
  { excel: "BAHTTEXT", syntax: "=BAHTTEXT(number)", category: "Text", oos: true, note: "Spells a number as Thai currency text." },
  { excel: "DBCS", syntax: "=DBCS(text)", category: "Text", oos: true, note: "Converts East Asian half-width characters to full-width." },
  { excel: "PHONETIC", syntax: "=PHONETIC(reference)", category: "Text", oos: true, note: "Extracts Japanese phonetic (furigana) text." },
  // The D* database family: filter with the Frame Filter node, then aggregate. Blocked
  // on the formula surface like VLOOKUP/MATCH (LEGACY_ALIASES); every superseded row
  // here must be a LEGACY_ALIASES key (functionReferenceLibs.test.ts pins it).
  { excel: "DAVERAGE", syntax: "=DAVERAGE(db, field, criteria)", category: "Database", superseded: true, note: "Use Frame Filter → AVERAGE." },
  { excel: "DCOUNT", syntax: "=DCOUNT(db, field, criteria)", category: "Database", superseded: true, note: "Use Frame Filter → COUNT." },
  { excel: "DCOUNTA", syntax: "=DCOUNTA(db, field, criteria)", category: "Database", superseded: true, note: "Use Frame Filter → COUNTA." },
  { excel: "DGET", syntax: "=DGET(db, field, criteria)", category: "Database", superseded: true, note: "Use XLOOKUP; the 'unique match only' rule is an Excel artifact." },
  { excel: "DMAX", syntax: "=DMAX(db, field, criteria)", category: "Database", superseded: true, note: "Use Frame Filter → MAX." },
  { excel: "DMIN", syntax: "=DMIN(db, field, criteria)", category: "Database", superseded: true, note: "Use Frame Filter → MIN." },
  { excel: "DPRODUCT", syntax: "=DPRODUCT(db, field, criteria)", category: "Database", superseded: true, note: "Use Frame Filter → PRODUCT." },
  { excel: "DSTDEV", syntax: "=DSTDEV(db, field, criteria)", category: "Database", superseded: true, note: "Use Frame Filter → STDEV.S." },
  { excel: "DSTDEVP", syntax: "=DSTDEVP(db, field, criteria)", category: "Database", superseded: true, note: "Use Frame Filter → STDEV.P." },
  { excel: "DSUM", syntax: "=DSUM(db, field, criteria)", category: "Database", superseded: true, note: "Use Frame Filter → SUM." },
  { excel: "DVAR", syntax: "=DVAR(db, field, criteria)", category: "Database", superseded: true, note: "Use Frame Filter → VAR.S." },
  { excel: "DVARP", syntax: "=DVARP(db, field, criteria)", category: "Database", superseded: true, note: "Use Frame Filter → VAR.P." },
  { excel: "LET", syntax: "=LET(name, value, ...)", category: "Excel 365", oos: true, note: "Node-graph wiring is the equivalent of named intermediate values" },
];
